### PR TITLE
being able to nest collections from the UI.

### LINKED ISSUE #1718: Collections: Drive data from nesting API for Add this collection to another collection modal
### Descriptive summary

Get the list of potential sub-collections for a collection from the nesting API.  Populate this list in the 'Add this collection to another collection' modal.

### Implementation

Update `app/views/hyrax/my/collections/_modal_add_collection_to_collection.html.erb` to use the nesting api to get the list of potential sub-collections through Hyrax::Collections::NestedCollectionQueryService.avilable_child_collections(parent: scope: limit_to_id: ).

### Steps to reproduce the behavior

1. Create a collection type that allows nesting via Dashboard -> Settings -> Collection Types
1. Create 3 collections of that type via Dashboard -> Collections -> New Collection -> select that new type -> add title and save
1. From Dashboard -> Collections, click the action menu for one of the new collections and select `Add collection to another collection`

Verify that the select list of the modal lists the other two collections.

### Related work

#1512 Created UI for collection in collection modal.

### PR DESCRIPTION
**Pull request by blancoj**
Fixes #1718 and #1707

### CODE REVIEW

File: app/controllers/hyrax/dashboard/nest_collections_controller.rb [hunk 1]
```diff
@@ -18,6 +21,19 @@ def create_within
...
       end
 
+      def process_nesting 
+        byebug
+         @parent_id = params[:parent_id]
+         @child_id = params[:child_id]
+         
+         parent_coll = Collection.find params[:parent_id]
+         child_coll = Collection.find params[:child_id]
+         parent_coll.add_member_objects ( params[:child_id] )
```
Comment (elrayle) [inline app/controllers/hyrax/dashboard/nest_collections_controller.rb]: You will want to use this instead of `add_member_objects`...
```
child_col1.member_of_collections << parent_col1
```
This sets up the inverse relationship `<child><pcdm:isMemberOf><parent>`

File: app/controllers/hyrax/dashboard/nest_collections_controller.rb [hunk 2]
```diff
@@ -18,6 +21,19 @@ def create_within
...
+   
+         #Not sure where to go from here.
+      end
```
Comment (elrayle) [inline app/controllers/hyrax/dashboard/nest_collections_controller.rb]: You will need to save the child for the indexing to make it into the solr doc.

@laritakr Is this what you would expect?  My testing in rails console required a save after setting member_of_collections.

File: app/models/concerns/hyrax/ability.rb [hunk 3]
```diff
@@ -57,6 +57,11 @@ def can_create_any_work?
       end && Hyrax::Collections::PermissionsService.admin_set_ids_for_user(user: current_user, access: ['deposit', 'manage'], ability: self).any?
     end
 
+    #Jose this is not needed after the refactor
+    #def can_deposit_in_collection?(collection)
+    #   Hyrax::Collections::PermissionsService.can_deposit_in_collection?(user: current_user, collection: collection)
+    #end
```
Comment (elrayle) [inline app/models/concerns/hyrax/ability.rb]: This should be removed before final PR.

File: app/views/hyrax/my/collections/index.html.erb [hunk 4]
```diff
@@ -20,7 +20,7 @@
 
     <% if can?(:create, Collection) && @collection_type_list_presenter.any? %>
       <% if @collection_type_list_presenter.many? %>
-        <% # modal to select type %>
+        <% # modal tadd-collection-to-collection-deny-modal select type %>
```
Comment (elrayle) [inline app/views/hyrax/my/collections/index.html.erb]: Not sure I see why the change to this comment.  Looks like it is still the collection type selection modal to me.

File: app/views/hyrax/my/_collection_action_menu.html.erb [hunk 5]
```diff
@@ -30,14 +31,18 @@
...
-      <%= link_to '#',
-        class: 'itemicon add-collection-to-collection',
-        title: t("hyrax.dashboard.my.action.add_collection_to_collection"),
-        data: { nestable: collection_presenter.collection_type_is_nestable? } do %>
-        <%= t("hyrax.dashboard.my.action.add_collection_to_collection") %>
-      <% end %>
-    </li>
+    <%# if no collecton types are nestable, then do not allow mapping option to show up. %>
+<% byebug %>
+    <% if Collection.all.map {|c| c.nestable? }.include?(true) %>
```
Comment (elrayle) [inline app/views/hyrax/my/_collection_action_menu.html.erb]: Is nestable? not available from solr doc?  I had to have to get the collection from Fedora just to determine if it is nestable.

File: app/views/hyrax/my/collections/_modal_add_collection_to_collection.html.erb [hunk 6]
```diff
@@ -1,26 +1,27 @@
...
-            <select class="form-control">
-              <option><%= t("hyrax.dashboard.my.action.select") %></option>
-              <option>Test collection hardcoded #1</option>
-              <option>Test collection hardcoded #2</option>
-            </select>
-          </div>
+          <label><%= t("hyrax.dashboard.my.action.select_collection") %></label>
+          <select name="parent_id">
+            <option value="none"><%= t("hyrax.dashboard.my.action.select") %></option>
+            <% colls = Hyrax::Collections::NestedCollectionQueryService.available_child_collections(parent: collection, scope: controller, limit_to_id: nil) %>
```
Comment (elrayle) [inline app/views/hyrax/my/collections/_modal_add_collection_to_collection.html.erb]: We should evaluate whether NestedCollectionQueryService can be adjusted to work with the collection id instead of a collection instance.  We should try to avoid having to get the collection from Fedora if we can.

**Comment by elrayle** [comment]
There is one failing test that is a known randomly failing test.  It is ok to merge.
