### PR TITLE
grant collection depositors read access to the collection

### LINKED ISSUE #1840: Collections: View and Deposit users should be able to see collection admin show page
### Descriptive summary

Users should be able to view the collection admin page for collections where they have View or Deposit access.

Users can see all collections for which they have Manage, View, and Deposit access in Dashboard -> Collections -> Managed Collections.  When a collection title is clicked for View or Deposit access collections, they are forwarded to the home page with a permissions error.

### Rationale

When given special access, the collection is likely of more interest and should be easily accessible by the user.

### Expected behavior

When user attempts to view a Deposit or View access collection, the collection's admin show page should be viewable.

When title is clicked and an attempt is made to view the page, the validation that should check view ability is...

```
can? :view_admin_show, collection
```

### Actual behavior

When user attempts to view a Deposit or View access collection, user is forwarded to home page and presented a no permissions message.

### Steps to reproduce the behavior

1. Create two users, user 1 and user 2.
1. Login as user 1
1. Create a collection with title 'Col - user 2 manage access' and grant user 2 Deposit access
1. Create a collection with title 'Col - user 2 deposit access' and grant user 2 Deposit access
1. Create a collection with title 'Col - user 2 view access' and grant user 2 Deposit access
1. Login as user 2
1. Dashboard -> Collections -> Managed Collections
1. click 'Col - user 2 manage access'

- [ ] Verify user is forwarded to the admin show page for collection 'Col - user 2 manage access'

1. click 'Col - user 2 deposit access'

- [ ] Verify user is forwarded to the admin show page for collection 'Col - user 2 deposit access'

1. click 'Col - user 2 view access'

- [ ] Verify user is forwarded to the admin show page for collection 'Col - user 2 view access'

### Related work

#1655 Added "Managed Collections" tab to dashboard
#1841 Show/hide buttons on admin show page based on abilities
#1843 Only show New Collection button if a user can create a collection
#1844 For major action buttons, should the UI hide, disable, or show dialog when user can't perform an action?

### PR DESCRIPTION
**Pull request by elrayle**
Fixes #1840

Grants read access to users/groups with deposit access for a collection.  It does not grant any additional access to works created in the collection.

This allows deposit users to view the admin show page.  They continue to only see works on the show page for which they already have view access (i.e. public works, works they created, and works shared with them).

[WIP] working on adjusting tests

@samvera/hyrax-code-reviewers

### CODE REVIEW

**Comment by jcoyne** [comment]
I  wouldn’t think we’d want depositors to see the admin show page since they’re not administrators. What’s the reasoning behind this change?

**Comment by elrayle** [comment]
The admin show page isn't really an 'admin' show page.  It is the page that gives you access to actions that can be taken on the collection.  For a depositor, this includes 'Add new work', 'Add existing works', 'Remove [work]', 'Create new collection as subcollection', 'Add a collection'.  The 'public' show page is the view that users see when they do not have any kind of special access (i.e. manage, deposit, view).

**Comment by jcoyne** [comment]
@elrayle thanks for the explanation. I forgot everything over the break. 😊

File: app/models/concerns/hyrax/collection_behavior.rb [hunk 1]
```diff
@@ -122,13 +122,16 @@ def permission_template
       Hyrax::PermissionTemplate.find_by!(source_id: id)
     end
 
-    # Calculate and update who should have edit access based on who
-    # has "manage" access in the PermissionTemplateAccess
+    # Calculate and update who should have read/edit access to the collections based on who
```
Comment (jcoyne) [inline app/models/concerns/hyrax/collection_behavior.rb]: It looks to me that this method overwrites any preexisting access controls assigned to this collection.  Is this the intended behavior?  If so, can we document that here?

Comment (elrayle) [reply app/models/concerns/hyrax/collection_behavior.rb]: Discussed in slack and the concern is about the name of the method not clearly conveying what the method is doing.  Changing name to reset_access_controls!

Comment (elrayle) [reply app/models/concerns/hyrax/collection_behavior.rb]: Request to change the name was created in issue #2455.
