### PR TITLE
Proxy deposit requests use valkyrie-specific query service when use_valkyrie? is true

### LINKED ISSUE #5456: Transferring ownership of work displays "NoMethodError in Hyrax::TransfersController#new" error message
### Descriptive summary

On nurax-pg, when I attempt to transfer ownership of one of my works, I see a "NoMethodError in Hyrax::TransfersController#new" message

### Expected behavior

Clicking "transfer ownership of work" should open Transfer Ownership page

### Actual behavior

Clicking "transfer ownership of work" generates "NoMethodError in Hyrax::TransfersController#new" error message

### Steps to reproduce the behavior

1. Make sure that transferring ownership is enabled on nurax-pg
2. Navigate to Dashboard -> Works
3. In the Actions menu next to a work, select "Transfer Ownership of Work"
4. Observe error message
hyraxtransferscontroller

### PR DESCRIPTION
**Pull request by cjcolvar**
I tried to replicate the behavior of WorkRelation where it should only retrieve objects of registered curation concerns (in `Hyrax::WorkResourceQueryService#work`), but I'm not sure if it is really necessary so I didn't write any tests for it yet.

I believe this should fix #5456

### CODE REVIEW

File: app/services/hyrax/work_resource_query_service.rb [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+      false
+    rescue Valkyrie::Persistence::ObjectNotFoundError
+      true
+    end
+
+    def work
+      # Need to ensure it is a work?
+      resource = Hyrax.query_service.find_by(id: id)
+      unless Hyrax.config.curation_concerns.include?(resource.class) ||
+             (resource.class.respond_to?(:_canonical_valkyrie_model) && Hyrax.config.curation_concerns.include?(resource.class._canonical_valkyrie_model)) # Wings-wrapped models
```
Comment (no-reply) [inline app/services/hyrax/work_resource_query_service.rb:28]: could `#name` be used instead? the ORMConverter base passes this through to `#_canonical_valkyrie_model` when appropriate. i think it would be something like ` unless Hyrax.config.curation_concerns.include?(resource.class.name)`

Comment (cjcolvar) [reply app/services/hyrax/work_resource_query_service.rb]: I had to change this to `#to_s` due to some failing tests where the Wings wrapping class returned `Hyrax::Work` for `#name` but `#to_s` returned `GenericWork`.

Comment (cjcolvar) [reply app/services/hyrax/work_resource_query_service.rb]: Ugh, more failing tests so might have to check both `#name` and `#to_s`.

File: app/services/hyrax/work_resource_query_service.rb [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+    def deleted_work?
+      Hyrax.query_service.find_by(id: id)
+      false
+    rescue Valkyrie::Persistence::ObjectNotFoundError
+      true
+    end
+
+    def work
+      # Need to ensure it is a work?
+      resource = Hyrax.query_service.find_by(id: id)
```
Comment (no-reply) [inline app/services/hyrax/work_resource_query_service.rb:26]: i'm still a little peeved (as i'm sure you must be too), to be doing all these checks. it feels like there should be one way to check if something is a registered "curation concern".

as an alternative thought, do we really need to check the registered concerns? i wonder if `resource.work?` wouldn't be good enough here.

Comment (cjcolvar) [reply app/services/hyrax/work_resource_query_service.rb:26]: I was thinking the same.  Checking `resource.work?` feels sufficient to me.  It broadens the number of matching resources but I don't think the check to ensure it is a registered curation concern and not merely a work is really that important.

Looking ahead at other uses of `WorkRelation.new.find` I wonder if replacing them all with a `query_service.find_by` and check for `#work?` is acceptable.

Comment (cjcolvar) [reply app/services/hyrax/work_resource_query_service.rb:26]: I went ahead and made the change to only test `#work?`.

**Review by no-reply — APPROVED** [review]
