### PR TITLE
Handle byte range requests for local files

### LINKED ISSUE #2815: Video playback not working in Safari
### Descriptive summary

For the 2.1.0 beta1 - Video is not playing back in Safari desktop or iOS, it is working in Chrome as expected. 

Audio is also playing back in both Safari Desktop and iOS

This link has both Audio and Video Files: https://nurax.curationexperts.com/concern/images/r494vk17h?locale=en

From: https://github.com/curationexperts/nurax/issues/204

### PR DESCRIPTION
**Pull request by cjcolvar**
Fixes #2815.

Byte-range requests in hyrax for derivatives is broken keeping Safari and iOS devices from showing audio and video.  This PR attempts to fix that.

TODO
Avoid overriding so much of Hydra::DownloadController
Avoid conditional logic in most methods
Add new tests for byte-range requests

@samvera/hyrax-code-reviewers

### CODE REVIEW

**Comment by jcoyne** [comment]
@cjcolvar Does this https://github.com/samvera/hydra-head/pull/427 fix the problem you are seeing?

**Comment by cjcolvar** [comment]
@jcoyne I don't think so, but that might be good to try for further improvement.  The issue here is that the byte-range request handling just wasn't happening for local files with `send_file` being used instead.
FWIW the documentation for `send_data` says that it is similar to `render plain: data` and does a slightly different render itself:
`render options.slice(:status, :content_type).merge(body: data)`

**Comment by cjcolvar** [comment]
I separated the overrides into a mixin module.  I think I prefer this approach over the prior commit but both pass the added tests.  I can squash the commits depending on the code review and the preferred approach.

File: app/controllers/hyrax/downloads_controller.rb [hunk 1]
```diff
@@ -1,6 +1,7 @@
 module Hyrax
   class DownloadsController < ApplicationController
     include Hydra::Controller::DownloadBehavior
+    include Hyrax::LocalFileDownloadsControllerBehavior
```
Comment (jenlindner) [inline app/controllers/hyrax/downloads_controller.rb]: 👍
