### PR TITLE
Hyrax-2259 - Admins should allow delete of permission_template_access…

### LINKED ISSUE #2259: valid_delete? for permission_template_access should allow delete for :view and :deposit access
Branch: master

### Descriptive summary

Hyrax::Admin::PermissionTemplateAccessesController #valid_delete? method prevents users from deleting the required admin_group managers.  It also prevents removing admin_group for viewers and depositors, but it shouldn't.

### Rationale

Admins have viewer and depositor access as managers.  A user can still add the admin_group as a viewer and/or depositor.  After adding, they should be able to remove the admin_group from viewer and depositor roles.

### Expected behavior

After adding the admin_group as a viewer/depositor, the user should be able to remove the admin_group from that role.  The Repository Administrators should be removed from the list of Viewers/Depositors.  And a flash message should display stating: 'The administrative set's participant rights have been updated'.

### Actual behavior

After adding the admin_group as a viewer/depositor, the user can NOT remove the admin_group from that role.  Clicking Remove causes flash message: 'The repository administrators group cannot be removed.' and the Repository Administrators remain listed under Viewers/Depositors.

### Steps to reproduce the behavior

1. Login as admin
1. Dashboard -> Administrative Sets -> click title of an admin set -> Edit -> Participants tab
1. group: admin  role: Depositor --> Add
1. click Remove beside Repository Administrators in Depositors list

- [ ] verify that Repository Administrators was removed form the list of Depositors
- [ ] verify a flash message is displayed: 'The administrative set's participant rights have been updated'

Repeat test for role: Viewer

### Related work

#2214 Don't allow the admin permission to be revoked
#2077 remove permission_template and permission_template_access entries when permission_template is deleted

### PR DESCRIPTION
**Pull request by fritzfreiheit**
Works in mediated workflow not listed as managed works for user with managing role

Fixes #2259

Change permission template access controller to use can? :destroy

Update [app/controllers/hyrax/admin/permission_template_accesses_controller.rb]:
* add authorize! :destroy, @permission_template_access to destroy method
* remove valid_delete? test from destroy method
* remove after_destroy_error from destroy method

Guidance for testing:
* (1) Login as admin
* (2) Create or find an admin set
* (3) Edit: Dashboard -> Administrative Sets -> click title of an admin set -> Edit -> Participants tab
* (4) Add group: 'admin' as: 'Depositor' --> Click Add
* (5) Under the Depositors section there should be a row for "Repository Administrators"
* (6) Click the "Remove" button at end of row in step 5.
* (7) Verify a flash message is display: 'The administrative set's participant rights have been updated'
* (8) Verify the "Repository Administrators" row under Depositors has been removed
* (9) Repeat steps 4 through 8 with 'Viewer' role replacing 'Depositor'

@samvera/hyrax-code-reviewers

### CODE REVIEW

File: app/controllers/hyrax/admin/permission_template_accesses_controller.rb [hunk 1]
```diff
@@ -5,31 +5,16 @@ class PermissionTemplateAccessesController < ApplicationController
...
+          @permission_template_access.destroy
           remove_access!
         end
-
-        if @permission_template_access.destroyed?
-          after_destroy_success
-        else
-          after_destroy_error
-        end
+        after_destroy_success if @permission_template_access.destroyed?
```
Comment (dlpierce) [inline app/controllers/hyrax/admin/permission_template_accesses_controller.rb:13]: What happens if it is not destroyed?

File: app/controllers/hyrax/admin/permission_template_accesses_controller.rb [hunk 2]
```diff
@@ -42,18 +27,6 @@ def after_destroy_success
         end
       end
 
-      def after_destroy_error
-        if source.admin_set?
```
Comment (elrayle) [inline app/controllers/hyrax/admin/permission_template_accesses_controller.rb:46]: I believe this is still needed.  There can still be an error that prevents the template access from being deleted.  If this happens, it should still redirect to the correct edit form and flash the error message.

File: app/controllers/hyrax/admin/permission_template_accesses_controller.rb (hunk 1 above)
Comment (fritzfreiheit) [reply app/controllers/hyrax/admin/permission_template_accesses_controller.rb:13]: See below.

File: app/controllers/hyrax/admin/permission_template_accesses_controller.rb (hunk 2 above)
Comment (fritzfreiheit) [reply app/controllers/hyrax/admin/permission_template_accesses_controller.rb:46]: I've fixed it.

**Review by dlpierce — APPROVED** [review]
