### PR TITLE
Warn user with pop-up modal of unsaved changes

### LINKED ISSUE #3911: Show confirmation before leaving unsaved changes in forms with tabs
### Descriptive summary

Edit forms for the following are presented as tabbed forms, which makes user to navigate from tab to tab while making changes.
1. Edit filesets
2. Edit pages in admin dashboard
3. Edit collections (#3454)

If the user leave the current tab with unsaved changes and make changes in the next tab and saves it, edits in the previous tab gets discarded.

### Rationale

The tab format misguides the user to think, hitting `Save` on the last tab will save the content entered in all the tabs.
For an example: When editing page contents for `About Page`, `Help Page` and the others (Admin dashboard -> Settings -> Pages), the changes in the previous tab are discarded when a user hits save in the current tab.

### Expected behavior

1. Notify user when leaving unsaved changes in the current tab, by using a pop-up
2. If the user confirms leaving the tab, navigate to the tab user wanted and reset the content in the previous tab
3. If not stay in the current tab

### Actual behavior

Change tabs when there are unsaved changes in the current tab. When clicked on the `Save` button in the next tab, the changes made in the previous tab are discarded.

### Steps to reproduce the behavior

Editing pages in admin dashboard;
1. As an admin, go to `Dashboard` -> `Settings` -> `Pages`
2. Change content in the `About Page` tab
3. Go to `Help Page` tab without saving the changes
4. Make some changes in the `Help Page` tab
5. Hit `Save` button
6. Go back to `About Page`, the changes made in the form are not saved

Editing filesets;
1. Go to `Dashboard` -> `Works`
2. Click on a work -> Go to items section on the bottom of the page -> `Select an action` -> `Edit`
3. Change the text in the form in `Descriptions` tab
4. Go to `Permissions` tab without saving the changes
5. Add a user and hit `Save` button at the bottom
6. Go back to `Descriptions` tab, the changes made were discarded

### Related work

[#2977](https://github.com/samvera/hyrax/pull/2799), [#2953](https://github.com/samvera/hyrax/pull/2953), #3910

### PR DESCRIPTION
**Pull request by Dananji**
Fixes #3911  ; refs #3454 

This uses the modal implementation in [#2977](https://github.com/samvera/hyrax/pull/2799), across the following scenarios.

Changes proposed in this pull request:
* Use confirmation when editing tabbed forms in Admin Pages, Collection edit, and File-set edit

Guidance for testing, such as acceptance criteria or new user interface behaviors:
* Dashboard -> Collections
* Choose 'Edit collection' from the drop-down for one collection in the list 
* Change a field in the `Description` tab
* Go to `Discovery` tab without saving the changes
* A modal pops up as follows;
modal-confirm
* Click `OK` to go to the `Discovery` tab OR click on modal backdrop/hit `ESC` button on keyboard to close the modal

@samvera/hyrax-code-reviewers

### CODE REVIEW

File: app/assets/javascripts/hyrax/nav_safety.js [hunk 1]
```diff
@@ -4,7 +4,9 @@
 // - Add the nav-safety class to the form element.
 
 Blacklight.onLoad(function() {
+  var clickedTab;
   $('.nav-safety-confirm').on('click', function(evt) {
+    clickedTab = $(this).attr('href');
```
Comment (adamjarling) [inline app/assets/javascripts/hyrax/nav_safety.js]: Just a thought @Dananji in the future, for shared convention if referring to a jQuery variable, how about doing `var $clickedTab = ...` instead of `var clickedTab = ...`?

Comment (Dananji) [reply app/assets/javascripts/hyrax/nav_safety.js]: Yes :+1: Thanks!
