### PR TITLE
Reindex the work during derivative creation if it is the work's thumbnail

### LINKED ISSUE #5504: Generate derivatives for FileSets when Valkyrie mode is enabled
### Descriptive summary

The pub/sub and transaction architecture doesn't currently generate derivatives for Valkyrie resources, resulting in no thumbnails or manifests.

### Rationale

Valkyrie resources should be able to generate derivatives.

### Expected behavior

Derivatives generate.

### Actual behavior

Derivatives don't generate.

#### Prerequisites

Configure Hyrax:

1. Edit /config/initializers/hyrax.rb and set:
```
  config.collection_model = "Hyrax::PcdmCollection"
  config.query_index_from_valkyrie = true
  config.index_adapter = :solr_index
```
2. restart rails app

#### To reproduce

1. Navigate to: Dashboard -> Works 
2. Click button: Add new work
3. Select type: Monograph
4. File in required metadata and other required steps
5. Add an image file
6. Click button: Save

This forwards to the new work's show page.  Look at the list of items at the bottom. There is no thumbnail.

### Related work

Found as part of https://github.com/samvera/hyrax/issues/5480

### PR DESCRIPTION
**Pull request by dlpierce**
### Fixes

Fixes #5504 

### Summary

Reindex the work during derivative creation if it is the work's thumbnail

### Guidance for testing, such as acceptance criteria or new user interface behaviors:
* A work's thumbnail is shown in the catalog view without re-saving the work after initial ingest.

@samvera/hyrax-code-reviewers

### CODE REVIEW

File: app/jobs/valkyrie_create_derivatives_job.rb [hunk 1]
```diff
@@ -1,23 +1,24 @@
...
-  end
-
-  def storage_adapter
-    Hyrax.storage_adapter
+  def reindex_parent(file_set_id)
+    file_set = Hyrax.query_service.find_by(id: file_set_id)
+    parent = Hyrax.custom_queries.find_parent_work(resource: file_set)
+    return unless parent.thumbnail_id == file_set.id
+    user = User.find_by_user_key(file_set.depositor)
+    Hyrax.publisher.publish('object.metadata.updated', object: parent, user: user)
```
Comment (no-reply) [inline app/jobs/valkyrie_create_derivatives_job.rb:22]: it doesn't seem right to publish `object.metadata.updated` here? we're not actually updating the object metadata.

if the goal is to reindex, shouldn't we just do that explicitly and avoid triggering other application behavior that might expect there to have been an actual change attributable to `user`?
 ```suggestion
    Hyrax.index_adapter.save(resource: parent)
```

Comment (no-reply) [reply app/jobs/valkyrie_create_derivatives_job.rb:22]: i think this also avoids the need to query for a user, who didn't really have anything to do with this change.

Comment (dlpierce) [reply app/jobs/valkyrie_create_derivatives_job.rb:22]: I was under the impression that publishing was the preferred way in general. Thanks for clearing that up.

Comment (no-reply) [reply app/jobs/valkyrie_create_derivatives_job.rb:22]: i think the contract with publishing events is that Hyrax will:
  - always publish them when the event occurs;
  - never publish them otherwise.

downstream applications need to be able to rely on events to trigger at the right times and not to invoke listener behavior when it's not appropriate.

**Review by tpendragon — APPROVED** [review]
