### PR TITLE
define Hyrax::ObjectNotFoundError

### LINKED ISSUE #3823: Define Hyrax::ObjectNotFoundError as a replacement for ActiveFedora::ObjectNotFoundError
### Descriptive summary

`ActiveFedora::ObjectNotFoundError` is raised and rescued in several places within Hyrax.  Create a new exception class defined in the Hyrax namespace that can be used as a replacement for `ActiveFedora::ObjectNotFoundError`.  The new class will be named `Hyrax::ObjectNotFoundError`.

### Code changes

- [ ] Define the new exceptions in lib/hyrax/errors.rb
- [ ] add it to the merged `:not_found` exceptions using `config.action_dispatch.rescue_responses.merge!` in lib/hyrax/engine.rb (_not completely sure this is necessary_)

### Related Work

Other issues will address the replacement usage involving these classes.

### PR DESCRIPTION
**Pull request by lsat12357**
Fixes #3823

Adds Hyrax::ObjectNotFoundError for use instead of ActiveFedora::ObjectNotFoundError.

### CODE REVIEW

File: lib/hyrax/errors.rb [hunk 1]
```diff
@@ -8,4 +8,6 @@ class MissingWorkflowError < HyraxError; end
   class WorkflowAuthorizationException < HyraxError; end
 
   class SingleUseError < HyraxError; end
+
+  class ObjectNotFoundError < HyraxError; end
```
Comment (no-reply) [inline lib/hyrax/errors.rb]: I think this needs to subclass `ActiveFedora::ObjectNotFoundError` so existing rescues continue to work?

How do we envision handling `Valkyrie::ObjectNotFoundError`?

Comment (lsitu) [reply lib/hyrax/errors.rb]: @no-reply Per your review comment above, I've added the changes to subclass ActiveFedora::ObjectNotFoundError and envision handling Valkyrie::ObjectNotFoundError. Could you review it? Thanks.

**Comment by lsitu** [comment]
@no-reply Yes, I think I can create another PR for it. Thanks.

**Comment by lsitu** [comment]
@no-reply I've updated the PR to raise Hyrax::ObjectNotFoundError instead while rescues existing ActiveFadora::ObjectNotFoundError and Valkyrie::Persistence:ObjectNotFoundError.

File: app/services/hyrax/thumbnail_path_service.rb [hunk 2]
```diff
@@ -24,7 +24,7 @@ def call(object)
         def fetch_thumbnail(object)
           return object if object.thumbnail_id == object.id
           Hyrax.query_service.find_by_alternate_identifier(alternate_identifier: object.thumbnail_id)
-        rescue Valkyrie::Persistence::ObjectNotFoundError
+        rescue Hyrax::ObjectNotFoundError
```
Comment (VivianChu) [inline app/services/hyrax/thumbnail_path_service.rb]: @lsitu - I'm wondering how come you replace Valkyrie::Persistence::ObjectNotFoundError with Hyrax::ObjectNotFoundError.  From the ticket, it mentions that use it to replace ActiveFedora::ObjectNotFoundError.  Thanks.

Comment (lsitu) [reply app/services/hyrax/thumbnail_path_service.rb]: @VivianChu I believe that's what `Hyrax::ObjectNotFoundError` is designed to handle, which will wrap up any such `ObjectNotFoundError` in Hyrax.

Comment (VivianChu) [reply app/services/hyrax/thumbnail_path_service.rb]: @lsitu - Thanks for the clarification.  LGTM 👍
