### PR TITLE
Workflow notifications for pending reviews

### LINKED ISSUE #936: Notifications for reviewer role going beyond the admin set
### Descriptive summary

Anyone with reviewer role on an admin set is getting the notifications for works submitted on ALL admin sets.
This issue exists in both the 1-0 stable and the master branch.

### Rationale

Users with the approving role should only get useful notifications. 

### Expected behavior

Anyone with the workflow role of reviewer on an admin set should be notified of works submitted to that admin set which they should review.

### Actual behavior

Anyone with the workflow role of reviewer on any admin set are getting notifications of works submitted to all admin sets.

### Steps to reproduce the behavior

I created two separate admin sets and 6 users with varying participant roles and workflow roles, and submitted works from each user who was able to submit to each admin set. Reviewers for only admin set 1 received notifications for works submitted to both admin sets. 

[Spreadsheet of users, roles, and what they were able to do in the app.](https://docs.google.com/spreadsheets/d/1zQsWlYMVs7gz6dHaOiXICygLj_5GTFOmbpI9MHRAq5o/edit#gid=0)

### PR DESCRIPTION
**Pull request by darrenleeweber**
Fixes #936 

This ensures that notifications to review/approve a new submission that belongs to an AdminSet are sent only to the managers associated with the AdminSet (cc to the depositor).

Changes proposed in this pull request:
* Use the entity workflow to query the AdminSet/PermissionTemplate associated with that workflow

@samvera/hyrax-code-reviewers

### CODE REVIEW

File: app/services/hyrax/workflow/notification_service.rb [hunk 1]
```diff
@@ -48,10 +48,18 @@ def send_notification(notification)
...
-          h[r.recipient_strategy] ||= []
-          h[r.recipient_strategy] += PermissionQuery.scope_users_for_entity_and_roles(entity: entity,
-                                                                                      roles: r.role)
+        case entity.workflow_state.name
+        when 'pending_review'
+          # notify the managers to review the deposit (CC depositors)
+          {
+            to: entity.workflow.permission_template.agent_ids_for(access: 'manage',  agent_type: 'user'),
+            cc: entity.workflow.permission_template.agent_ids_for(access: 'deposit', agent_type: 'user')
+          }
```
Comment (darrenleeweber) [inline app/services/hyrax/workflow/notification_service.rb]: Not sure if this Hash return value supports indifferent access or if the keys must be strings.  If the latter, this PR needs to be updated to use strings.

Comment (darrenleeweber) [inline app/services/hyrax/workflow/notification_service.rb]: Also not sure if the notification recipients should include groups.  I've left out groups because there are no email addresses associated with a Hyrax::Group (AFAICT).

Comment (jcoyne) [inline app/services/hyrax/workflow/notification_service.rb]: I think this is fine for now. As far as I know @laritakr is still working on the group abstraction.

Comment (laritakr) [inline app/services/hyrax/workflow/notification_service.rb]: @jcoyne not at the moment (I'm on the collections sprints), but we consider it to be part of the roles & permissions work.
