### PR TITLE
fix dashboard -> collection not showing collections created as valkyrie resources

### LINKED ISSUE #5281: newly created Hyrax::PcdmCollection not in dashboard -> collections
### Descriptive summary

If you create a collection as a Hyrax::PcdmCollection, it does not show up in the Dashboard -> Collections listing under Your Collections.  It is in All Collections for admins.

### Rationale

Collections should be listed in the dashboard regardless of what collection class was used during creation.

### Expected behavior

A collection created using Hyrax::PcdmCollection should be listed in Dashboard -> Collections -> Your Collections.

### Actual behavior

A collection created using Hyrax::PcdmCollection is NOT listed in Dashboard -> Collections -> Your Collections.  It is listed in All Collections for admins indicating it was successfully created and indexed.

### Steps to reproduce the behavior

Prerequisite:
* set `config.collection_model = 'Hyrax::PcdmCollection'` in `/config/initializers/hyrax.rb`

To reproduce:
1. login
2. Dashboard -> Collections -> New Collection -> set title and save
3. Dashboard -> Collections -> Your Collections

Note that the new collection is not listed.

### Related work

Issue  #5132 - Val MVP: Create PcdmCollection as a valkyrie resource through UI

### PR DESCRIPTION
**Pull request by elrayle**
Fixes #5281

Always includes `::Collection` when creating model filters for collections.  Otherwise, collections created with `Hyrax::PcdmCollection` will not be found by the search.  So all searches for collections should include `[::Collection, Hyrax.config.collection_class].uniq`, which will include `Hyrax::PcdmCollection` when it is the configured class.

@samvera/hyrax-code-reviewers

### CODE REVIEW

File: app/search_builders/hyrax/dashboard/collections_search_builder.rb [hunk 1]
```diff
@@ -9,7 +9,7 @@ class CollectionsSearchBuilder < Hyrax::CollectionSearchBuilder
 
       # This overrides the models in FilterByType
       def models
-        [::AdminSet, ::Collection, Hyrax.config.collection_model.safe_constantize].uniq.compact
+        [::AdminSet, ::Collection, Hyrax.config.collection_class].uniq.compact
```
Comment (elrayle) [inline app/search_builders/hyrax/dashboard/collections_search_builder.rb:12]: This is not part of the fix.  It updated the code for consistency `collection_class` is already constantized in `Hyrax.config`

File: lib/hyrax/configuration.rb [hunk 2]
```diff
@@ -707,7 +707,7 @@ def collection_model
     ##
     # @return [Class] the configured collection model class
     def collection_class
-      collection_model.constantize
+      collection_model.safe_constantize
```
Comment (elrayle) [inline lib/hyrax/configuration.rb:710]: Switch to `safe_constantize` to catch the case where an invalid model is set in `collection_model`.

File: app/search_builders/hyrax/my/collections_search_builder.rb [hunk 3]
```diff
@@ -21,6 +21,6 @@ def show_only_collections_deposited_by_current_user(solr_parameters)
   # This overrides the models in FilterByType
   # @return [Array<Class>] a list of classes to include
   def models
-    [::AdminSet, Hyrax::AdministrativeSet, Hyrax.config.collection_model.safe_constantize].compact
+    [::AdminSet, Hyrax::AdministrativeSet, ::Collection, Hyrax.config.collection_class].uniq.compact
```
Comment (elrayle) [inline app/search_builders/hyrax/my/collections_search_builder.rb:24]: This is the fix that allows all the user's collections to appear in the Dashboard -> Collections list.

**Review by dlpierce — APPROVED** [review]
