### PR TITLE
enforces only to use wings adapter for now

### LINKED ISSUE #3654: Hyrax configuration for wings metadata adapter
### Descriptive summary

Raise exception in the `setter` related to Wings metadata adapter so that the app fails if the value is anything but `:wings_adapter` to notify the user that Hyraxes `valkryie_metadata_adapter` is currently only supporting the wings.

### PR DESCRIPTION
**Pull request by revgum**
Fixes #3654 

Circle CI configuration change notes;
- Originally if any files in the PR changed `hyrax/generators` then the internal test app wouldn't be generated. Changed to be the inverse, so that the internal test app is forced to be rebuilt when any generator file had changes. 
- Because Circle CI is configured to cache the internal test app directory, it should be restored and functional across test suite runs until a PR includes changes to a `hyrax/generators` file.

### CODE REVIEW

File: lib/hyrax/configuration.rb [hunk 1]
```diff
@@ -227,9 +227,13 @@ def curation_concerns
     # @see lib/wings
     # @see https://github.com/samvera-labs/valkyrie
     def valkyrie_metadata_adapter
-      Valkyrie::MetadataAdapter.find(@valkyrie_metadata_adapter || :wings_adapter)
+      Valkyrie::MetadataAdapter.find(@valkyrie_metadata_adapter)
```
Comment (no-reply) [inline lib/hyrax/configuration.rb]: looks like we still need the default, here.

We could (should?) also get a default into the generator for the config. But either way, we'd need this to support apps that generated their config with an older version,

**Comment by revgum** [comment]
@no-reply ping
