### PR TITLE
Collection Types: Settings should be read only if any collections of a type exist

### LINKED ISSUE #1531: Collection Types: Settings should be read only if any collections of a type exist
### Descriptive summary

Make sure that in the collection type edit form's Settings tab, when a collection type is being edited AND there are collections of that type THEN all settings are readonly.

### Rationale

For at least the initial implementation, there will be no code that provides a migration path for existing collections to change behaviors associated with settings once the collection exists.  Therefore, we are disallowing changes to settings for collection types once a collection of that type is created.

### Expected behavior

When editing a collection type and viewing the Settings tab, all settings will be READONLY (i.e., disabled and grayed out) if there are any collections of that type.

### Implementation Note

[Hyrax::CollectionType](https://github.com/samvera/hyrax/blob/collections-sprint/app/models/hyrax/collection_type.rb) #collections? method can be used to determine if collections exist for a type.

### Steps to reproduce the behavior

1. Dashboard -> Settings -> Collection Type -> Create collection type
  1. add metadata and save
  1. on Settings tab, note settings values
  1. save (may need to cancel to get back out to index)
1. Dashboard -> Settings -> Collection Type -> click Edit beside type created in first step
  1. click Settings tab
  1. change settings
  1. save (may need to cancel to get back out to index)

Verify you were able to change settings.

1. Dashboard -> Repository Contents -> Collections -> Create a collection -> in modal, select the type created in the first step
  1. add title and save
1. Dashboard -> Settings -> Collection Type -> click Edit beside type created in first step
  1. click Settings tab

Verify that all checkbox settings are disabled and grayed out.

### Dependency

#1506 Collections: Show modal for selecting collection type when New Collection
#1341 adding implementation of Hyrax::Collections #collections (list of all collections of a type) and #collections? (count of all collections of a type).  PR coming soon.

### Related Work

#1346 Collection Types: Create configuration settings partial of the new/edit form
#1530 Collection Types: Admin Set Settings should always be readonly

### PR DESCRIPTION
**Pull request by respinos**
Fixes #1531

Present tense short summary (50 characters or less)

More detailed description, if necessary. Try to be as descriptive as you can: even if you think that the PR content is obvious, it may not be obvious to others. Include tracebacks if helpful, and be sure to call out any bits of the PR that may be work-in-progress.

If a collection type has collections, its settings fields should be read-only:

* CollectionType: limit before_save to prevent updates to settings
* force settings inputs to be disabled if collectiontype has collections
* fix collection type settings partial tests

@samvera/hyrax-code-reviewers

### CODE REVIEW

File: app/models/hyrax/collection_type.rb [hunk 1]
```diff
@@ -109,5 +109,22 @@ def ensure_no_collections
         errors[:base] << I18n.t('hyrax.admin.collection_types.error_not_empty')
         throw :abort
       end
+
+      def ensure_no_settings_changes
+        return true unless collections?
+        return true unless
+            self.changes.has_key?('nestable') or
```
Comment (mjgiarlo) [inline app/models/hyrax/collection_type.rb]: Would you consider refactoring this to look like the following?

```ruby
['nestable', 'discoverable', 'sharable', 'allow_multiple_membership', 'require_membership', 'assigns_workflow', 'assigns_visibility'].any? do |key|
  key.in?(changes)
end
```

File: spec/models/hyrax/collection_type_spec.rb [hunk 2]
```diff
@@ -129,13 +129,25 @@
     end
   end
 
+  describe "save (no settings changes)" do
+    before do
+      allow(collection_type).to receive(:collections?).and_return(true)
+    end
+
+    it "succeeds no changes to settings are being made" do
+      expect(collection_type.save).to be_truthy
```
Comment (mjgiarlo) [inline spec/models/hyrax/collection_type_spec.rb]: You can make this even more reliable by changing `be_truthy` to `be true`

File: spec/models/hyrax/collection_type_spec.rb [hunk 3]
```diff
@@ -129,13 +129,25 @@
...
   describe "save" do
     before do
       allow(collection_type).to receive(:collections?).and_return(true)
+      allow(collection_type).to receive(:changes).and_return({'nestable' => false})
     end
 
-    it "fails if collections exist of this type" do
-      expect(collection_type.save).to eq false
+    it "fails if collections exist of this type and settings are changed" do
+      expect(collection_type.save).to be_falsey
```
Comment (mjgiarlo) [inline spec/models/hyrax/collection_type_spec.rb]: Would `be false` also work here? (Sorry, I am a `truthy`/`falsey` hater!)

File: spec/views/hyrax/admin/admin_sets/_form.html.erb_spec.rb [hunk 4]
```diff
@@ -2,6 +2,8 @@
   let(:admin_set) { stub_model(AdminSet) }
   let(:form) { Hyrax::Forms::AdminSetForm.new(admin_set, double, double) }
 
+  context ""
```
Comment (mjgiarlo) [inline spec/views/hyrax/admin/admin_sets/_form.html.erb_spec.rb]: Cruft? TODO?

File: spec/views/hyrax/admin/collection_types/_form_settings.html.erb_spec.rb [hunk 5]
```diff
@@ -8,24 +21,47 @@
...
+    it "renders the intructions and warning" do
+      expect(rendered).to match(I18n.t("hyrax.admin.collection_types.form_settings.instructions"))
+      expect(rendered).to match(I18n.t("hyrax.admin.collection_types.form_settings.warning"))
+    end
+
+    INPUT_IDS.each do |id|
+      it "renders the #{id} checkbox to be disabled" do
+        match = rendered.match(/(<input.*id="#{id}".*>)/)
+        expect(match).not_to be_nil
+        next if match.nil?
```
Comment (mjgiarlo) [inline spec/views/hyrax/admin/collection_types/_form_settings.html.erb_spec.rb]: If line 40 will fail is `match` is `nil`, do we need this `next` on line 41?

File: spec/views/hyrax/admin/collection_types/_form_settings.html.erb_spec.rb [hunk 6]
```diff
@@ -8,24 +21,47 @@
...
+      assign(:form, collection_type_form)
+      allow(view).to receive(:f).and_return(form)
+      render
+    end
+
+    INPUT_IDS.each do |id|
+      it "renders the #{id} checkbox to be disabled" do
+        match = rendered.match(/(<input.*id="#{id}".*>)/)
+        expect(match).not_to be_nil
+        next if match.nil?
```
Comment (mjgiarlo) [inline spec/views/hyrax/admin/collection_types/_form_settings.html.erb_spec.rb]: If line 60 will fail if `match` is `nil`, do we need this `next` on line 61?

File: spec/views/hyrax/admin/collection_types/_form_settings.html.erb_spec.rb [hunk 7]
```diff
@@ -8,24 +21,47 @@
...
 
-  it "renders the checkboxes" do
-    expect(rendered).to have_selector("input#collection_type_nestable")
-    expect(rendered).to have_selector("input#collection_type_discoverable")
-    expect(rendered).to have_selector("input#collection_type_sharable")
-    expect(rendered).to have_selector("input#collection_type_require_membership")
-    expect(rendered).to have_selector("input#collection_type_allow_multiple_membership")
-    expect(rendered).to have_selector("input#collection_type_assigns_workflow")
-    expect(rendered).to have_selector("input#collection_type_assigns_visibility")
+  context "collection_type.collections? is true" do
```
Comment (mjgiarlo) [inline spec/views/hyrax/admin/collection_types/_form_settings.html.erb_spec.rb]: Would you consider renaming the `context` to `when collection_type.collections? is true`? The rspec output reads more idiomatically when `context` blocks begin with e.g., `when` or `with`.

File: spec/views/hyrax/admin/collection_types/_form_settings.html.erb_spec.rb [hunk 8]
```diff
@@ -8,24 +21,47 @@
     end
   end
 
-  before do
-    assign(:form, collection_type_form)
-    allow(view).to receive(:f).and_return(form)
-    render
-  end
+  context "collection_type.collections? is false" do
```
Comment (mjgiarlo) [inline spec/views/hyrax/admin/collection_types/_form_settings.html.erb_spec.rb]: Would you consider renaming the `context` to `when collection_type.collections? is false`? The rspec output reads more idiomatically when `context` blocks begin with e.g., `when` or `with`.

File: app/models/hyrax/collection_type.rb [hunk 9]
```diff
@@ -109,5 +109,18 @@ def ensure_no_collections
         errors[:base] << I18n.t('hyrax.admin.collection_types.error_not_empty')
         throw :abort
       end
+
+      def ensure_no_settings_changes
+        return true unless collections?
+        return true unless
```
Comment (mjgiarlo) [inline app/models/hyrax/collection_type.rb]: The indenting looks a bit funky here. I would consider reworking this as follows:

```ruby
def ensure_no_settings_changes
  # ...
  return true if collection_type_properties_changed?
  errors[:base] << ...
  # ...
end

def collection_type_properties_changed?
  ['nestable', 'discoverable', 'sharable', 'allow_multiple_membership', 'require_membership', 'assigns_workflow', 'assigns_visibility'].any? do |key|
     key.in?(changes)
  end
end
```

File: spec/views/hyrax/admin/collection_types/_form_settings.html.erb_spec.rb (hunk 5 above)
Comment (respinos) [inline spec/views/hyrax/admin/collection_types/_form_settings.html.erb_spec.rb]: To avoid a Ruby error with the following line (`match[1]`) if `match` is indeed nil. May not be necessary?

File: spec/views/hyrax/admin/collection_types/_form_settings.html.erb_spec.rb (hunk 7 above)
Comment (respinos) [inline spec/views/hyrax/admin/collection_types/_form_settings.html.erb_spec.rb]: OK.

File: app/models/hyrax/collection_type.rb (hunk 9 above)
Comment (respinos) [inline app/models/hyrax/collection_type.rb]: Sure. That's a `return true unless...`, though, right?

Comment (respinos) [inline app/models/hyrax/collection_type.rb]: (That's what the spec says :-)

File: spec/models/hyrax/collection_type_spec.rb [hunk 10]
```diff
@@ -129,13 +129,25 @@
     end
   end
 
+  describe "save (no settings changes)" do
+    before do
+      allow(collection_type).to receive(:collections?).and_return(true)
+    end
+
+    it "succeeds no changes to settings are being made" do
+      expect(collection_type.save).to be true
```
Comment (cjcolvar) [inline spec/models/hyrax/collection_type_spec.rb]: I think the preferred version of this is now `be_truthy`.

File: spec/models/hyrax/collection_type_spec.rb [hunk 11]
```diff
@@ -129,13 +129,25 @@
...
   describe "save" do
     before do
       allow(collection_type).to receive(:collections?).and_return(true)
+      allow(collection_type).to receive(:changes).and_return({'nestable' => false})
     end
 
-    it "fails if collections exist of this type" do
-      expect(collection_type.save).to eq false
+    it "fails if collections exist of this type and settings are changed" do
+      expect(collection_type.save).to be false
```
Comment (cjcolvar) [inline spec/models/hyrax/collection_type_spec.rb]: I think the preferred version of this is now `be_falsey`.

File: app/models/hyrax/collection_type.rb [hunk 12]
```diff
@@ -109,5 +109,19 @@ def ensure_no_collections
...
+
+      def ensure_no_settings_changes
+        return true unless collections?
+        return true unless collection_type_properties_changed?
+        errors[:base] << I18n.t('hyrax.admin.collection_types.error_settings_changes')
+        throw :abort
+      end
+
+      def collection_type_properties_changed?
+        ['nestable', 'discoverable', 'sharable', 'allow_multiple_membership', 'require_membership', 'assigns_workflow', 'assigns_visibility'].any? do |key|
```
Comment (cjcolvar) [inline app/models/hyrax/collection_type.rb]: I think a slightly simpler version of this would be using the intersection instead of any?:
(property_keys & changes.keys).present?

File: spec/views/hyrax/admin/collection_types/_form_settings.html.erb_spec.rb (hunk 5 above)
Comment (mjgiarlo) [inline spec/views/hyrax/admin/collection_types/_form_settings.html.erb_spec.rb]: @respinos Yeah, I think it is indeed unnecessary. You shouldn't ever get to `match[1]` if `match` is indeed `nil`.

File: app/models/hyrax/collection_type.rb (hunk 12 above)
Comment (mjgiarlo) [inline app/models/hyrax/collection_type.rb]: @cjcolvar Agree. That was similar to my most recent suggestion, but I fear that editing comments multiple times (as I am wont to do as I change my mind...) means that they're easy to miss. I might prefer `any?` to `present?` here, but I really dig the intersection approach.

**Comment by elrayle** [comment]
@mjgiarlo @cjcolvar You want to take another look at this.  I added a second commit that does special processing for admin_sets and user_collections.

File: spec/models/hyrax/collection_type_spec.rb [hunk 13]
```diff
@@ -142,13 +142,44 @@
...
+        allow(collection_type).to receive(:collections?).and_return(false)
+      end
+
+      it 'fails if settings are changed' do
+        expect(collection_type.save).to be false
+        expect(collection_type.errors).not_to be_empty
+      end
+    end
+
+    context 'for admin set collection type' do
```
Comment (cjcolvar) [inline spec/models/hyrax/collection_type_spec.rb]: This should be `user collection type`.

File: app/models/hyrax/collection_type.rb [hunk 14]
```diff
@@ -110,17 +108,33 @@ def ensure_no_collections
         throw :abort
       end
 
-      def ensure_no_settings_changes
+      def ensure_no_settings_changes_for_admin_set_type
+        return true unless admin_set? && exists_for_machine_id?(ADMIN_SET_MACHINE_ID)
```
Comment (cjcolvar) [inline app/models/hyrax/collection_type.rb]: I don't quite understand what is being checked here.  Is this the same as `unless admin_set? && persisted?`?  Why do you need to check for existence because modifying admin_set settings is always forbidden, right?

If you don't need to check existence I think these three cases could be collapsed together.

**Comment by elrayle** [comment]
Failure was randomly occurring known batch edit failure.
