### PR TITLE
Move Hydra:AccessControl conversion to a valkyrie resource into ModelTransformer

### LINKED ISSUE #4901: Indexing of Monograph (Valkyrie resource) into the Valkyrie solr core does not include permissions
### Descriptive summary

Include what version of Hyrax relates to this issue (7.x, 6.x, HEAD, etc.) if appropriate, and any relevant tracebacks if you're reporting a bug.

### Rationale

Solr docs should be the same whether created through ActiveFedora or Valkyrie indexing.

### Expected behavior

6th field down is the permission giving the depositor edit access: `"edit_access_person_ssim":["admin@example.com"]`

```
      {
        "id":"37720c723",
        "created_at_dtsi":"2021-04-30T13:00:48Z",
        "updated_at_dtsi":"2021-04-30T13:00:54Z",
        "has_model_ssim":["Monograph"],
        "human_readable_type_tesim":["Monograph"],
        "edit_access_person_ssim":["admin@example.com"],
        "visibility_ssi":"restricted",
        "title_tesim":["m30-01"],
        "suppressed_bsi":false,
        "admin_set_id_ssim":["admin_set/default"],
        "member_ids_ssim":["1544bp08d"],
        "depositor_ssim":["admin@example.com"],
        "depositor_tesim":["admin@example.com"],
        "creator_tesim":["me"],
        "date_created_tesim":[""],
        "keyword_tesim":[""],
        "related_url_tesim":[""],
        "resource_type_tesim":[""],
        "subject_tesim":[""],
        "record_info_tesim":["asdf"],
        "_version_":1698470460267692032,
        "timestamp":"2021-04-30T13:00:55.131Z",
        "score":1.7917595}
```

### Actual behavior

The permission for the depositor is missing form the solr doc.

```
      {
        "id":"37720c723",
        "created_at_dtsi":"2021-04-30T13:00:48Z",
        "updated_at_dtsi":"2021-04-30T13:00:48Z",
        "has_model_ssim":["Monograph"],
        "human_readable_type_tesim":["Monograph"],
        "visibility_ssi":"restricted",
        "title_tesim":["m30-01"],
        "suppressed_bsi":false,
        "admin_set_id_ssim":["admin_set/default"],
        "member_ids_ssim":["1544bp08d"],
        "depositor_ssim":["admin@example.com"],
        "depositor_tesim":["admin@example.com"],
        "creator_tesim":["me"],
        "date_created_tesim":[""],
        "keyword_tesim":[""],
        "related_url_tesim":[""],
        "resource_type_tesim":[""],
        "subject_tesim":[""],
        "record_info_tesim":["asdf"],
        "_version_":1698470460458532864,
        "timestamp":"2021-04-30T13:00:55.314Z",
        "score":0.6931471}
```

#### Prerequisites

Edit the hyrax initializer in the test app (e.g. `.internal_test_app/config/initializers/hyrax.rb` or `.dassie/cofig/initializers/hyrax.rb`) and set config

```
  config.query_index_from_valkyrie = true
```

#### Steps
1. Login
2. Click Share Work on Home page
3. Select Monograph as type of work
4. Fill in required fields and add file.
5. Save

View solr doc created by Valkyrie indexing and look for "edit_access_person_ssim" with the value being the email address of the user that created the Monograph.

### Related work

Issue  #4487 - Solr docs generated by ActiveFedora and Hyrax::ValkyrieWorkIndexer are not compatible
Issue #4900 - Edit form error when setting Sharing permissions
Issue #4899 - Edit form with Monograph (Valkyrie resource) fails to display all fields in the Descriptions tab

### PR DESCRIPTION
**Pull request by cjcolvar**
wings.rb was defining #valkyrie_resource directly on
Hydra::AccessControl but the query service is attempting to convert
using ModelTransformer which doesn't know how to handle AccessControl
objects.  Getting rid of the direct method declaration in favor of
Valkyrizable standardizes and solves this problem.

Fixes #4901

@samvera/hyrax-code-reviewers

### CODE REVIEW

File: lib/wings/model_transformer.rb [hunk 1]
```diff
@@ -110,7 +110,7 @@ def fetch(key)
     private
 
     def mint_id
-      id = pcdm_object.assign_id
+      id = pcdm_object.try(:assign_id)
```
Comment (cjcolvar) [inline lib/wings/model_transformer.rb:113]: `Hydra::AccessControl#assign_id` is a private method so just try here and don't assign an id.  Is this okay or should this be changed to `send(:assign_id)`?

Comment (no-reply) [reply lib/wings/model_transformer.rb:113]: this seems good to me.

**Comment by no-reply** [comment]
this is a great fix. i think it will also fix a recurring error in dev environments where ActiveFedora reports a type mismatch ("expected `Hydra::AccessControl` got `Hydra::AccessControl`" 😱 ).

**Review by no-reply — APPROVED** [review]
approved pending spec pass.
