### PR TITLE
Restrict visibility options based on AS template.

### LINKED ISSUE #1801: Can't add a work to an admin set with an Admin set fixed release date setting that has passed
**Descriptive summary**

When trying to add a work to an Admin set with a fixed release date setting that has passed, the work "disappears".

**Expected behavior:**
When date of embargo setting passes on the Admin set, one can still submit a work.

**Steps to reproduce the behavior**

1. Submit a work to an Admin set with an expired release date. Can use Nurax Admin Sets 16, 17, 18
2. Work disappears, page reloads to blank and work is not deposited. Similar in behavior to https://github.com/samvera/hyrax/issues/1772

moved from https://github.com/curationexperts/nurax/issues/108

### PR DESCRIPTION
**Pull request by jonathandixon**
Fixes #1801 

When trying to add a work to an Admin set with a fixed release date setting that has passed, the work fails server-side validation. 

Changes proposed in this pull request:
* When the selected admin set has a release date that has passed, force the user to select a valid visibility (not lease or embargo). 
* If a disabled visibility option is selected then automatically change the selection to least public option that is enabled.

@samvera/hyrax-code-reviewers

### CODE REVIEW

**Comment by mjgiarlo** [comment]
@tdonohue Can you give this small PR a quick code review?

File: spec/javascripts/visibility_component_spec.js [hunk 1]
```diff
@@ -169,6 +169,25 @@ describe("VisibilityComponent", function() {
         expect(target.requireEmbargo).toHaveBeenCalledWith("authenticated", futureDate);
       });
     });
+    describe("with required past release date, dont restrict visibility", function() {
+      beforeEach(function() {
+        spyOn(target, 'disableEmbargoAndLease');
+      });
+      it("require visibility", function() {
```
Comment (tdonohue) [inline spec/javascripts/visibility_component_spec.js]: Tiny thing, but this `it` description is incorrect. Looks like it should say "require immediate release" or "disable embargo and lease"

File: app/assets/javascripts/hyrax/save_work/visibility_component.es6 [hunk 2]
```diff
@@ -255,6 +266,16 @@ export default class VisibilityComponent {
     return this.element.find("select[id$='_visibility_after_embargo']")
   }
 
+  // If the selected visibility option is disabled change selection to the
+  // least public option that is enabled.
+  checkEnabledVisibilityOption() {
```
Comment (tdonohue) [inline app/assets/javascripts/hyrax/save_work/visibility_component.es6]: This new method should probably have specs
