### PR TITLE
Do not throw an error when encountering an unversioned file Fixes #1404

### LINKED ISSUE #1404: file_set_audit_service fails when a file does not have versions
### Descriptive summary

In Hyrax 1.x, the `Hyrax::RepositoryAuditService.audit_everything` service fails when it encounters a file that does not have versions. The error is:
```
NoMethodError: undefined method `each' for #<Hydra::PCDM::File:0x007fcb513bcf80>
/Users/bess/.rvm/gems/ruby-2.3.3@hyrax/gems/activemodel-5.0.4/lib/active_model/attribute_methods.rb:433:in `method_missing'
/Users/bess/.rvm/gems/ruby-2.3.3@hyrax/gems/hyrax-1.0.3/app/services/hyrax/file_set_audit_service.rb:64:in `audit_file'
```
The bug can be fixed by checking to see whether the audit is being run on a file or a version set:
```
[60, 69] in /Users/bess/.rvm/gems/ruby-2.3.3@hyrax/gems/hyrax-1.0.3/app/services/hyrax/file_set_audit_service.rb
   60:       # @param [ActiveFedora::File] file to audit
   61:       # @param [Array] log container for messages
   62:       def audit_file(file, log = [])
   63:         byebug
   64:         versions = file.has_versions? ? file.versions.all : file
=> 65:         versions.each { |v| log << audit_file_version(file.id, v.uri) }
   66:         log
   67:       end
   68:
   69:       # Retrieve or generate the audit check for a file and provide a human-readable status message.
(byebug) versions
#<Hydra::PCDM::File uri="http://127.0.0.1:8984/rest/dev/57/12/m6/52/5712m6524/files/04f5e37d-0f0a-4033-a67d-e260b08bf01e" >
(byebug) versions.uri
#<RDF::URI:0x3fd3eaaf2564 URI:http://127.0.0.1:8984/rest/dev/57/12/m6/52/5712m6524/files/04f5e37d-0f0a-4033-a67d-e260b08bf01e>
(byebug) audit_file_version(file.id, versions.uri)
#<ChecksumAuditLog id: nil, file_set_id: "5712m6524", file_id: "5712m6524/files/04f5e37d-0f0a-4033-a67d-e260b08bf0...", version: "http://127.0.0.1:8984/rest/dev/57/12/m6/52/5712m65...", pass: 999, expected_result: nil, actual_result: nil, created_at: nil, updated_at: nil>
```

### PR DESCRIPTION
**Pull request by bess**
Fixes #1404 
Resubmitted incorporating @mjgiarlo's suggestions and now with test coverage.

Thanks!

@samvera/hyrax-code-reviewers

### CODE REVIEW

File: app/services/hyrax/file_set_audit_service.rb [hunk 1]
```diff
@@ -60,8 +60,11 @@ def stat_to_string(stat)
       # @param [ActiveFedora::File] file to audit
       # @param [Array] log container for messages
       def audit_file(file, log = [])
-        versions = file.has_versions? ? file.versions.all : file
-        versions.each { |v| log << audit_file_version(file.id, v.uri) }
+        if file.has_versions?
```
Comment (mjgiarlo) [inline app/services/hyrax/file_set_audit_service.rb]: @bess What would you think of simplifying the code changes made in this branch to better align with the related code in `master` (which should not be vulnerable to the same buggy behavior):

https://github.com/samvera/hyrax/blob/master/app/services/hyrax/file_set_fixity_check_service.rb#L79

You could patch line 63 as follows:

```ruby
version = file.has_versions?  file.versions.all : Array.wrap(file)
```

As for how to test it, take a look at this related code in `master`:

https://github.com/samvera/hyrax/blob/master/spec/services/hyrax/file_set_fixity_check_service_spec.rb#L10-L28

Happy to chat more about this, and have time tomorrow. Thanks for working on this!

**Comment by bess** [comment]
@mjgiarlo This is ready for another review. Thank you!

**Comment by mjgiarlo** [comment]
Thx, @bess!
