### PR TITLE
Backporting fix of logic around deleting nested membership

### LINKED ISSUE #4193: Allow ContentEventJob to receive either an ActiveFedora object or a Valkyrie resource
### Descriptive summary
Convert ContentEventJob to allow it to receive either an ActiveFedora based object or a Valkyrie::Resource equivalent object.

### Rationale
Allow jobs to execute correctly with existing AF implementation or the Wings Valkyrie implementation.

### Expected behavior
ContentEventJob receives a Valkyrie::Resource and performs the action.

### Actual behavior
ContentEventJob raises an exception when passed a Valkyrie::Resource.

### Approach for Conversion
[See Pattern for Jobs Receiving Parameter that may be an AF Object or a Valkyrie Resource](https://docs.google.com/document/d/1f9yDjtkXapFf1DYLyPhprnB4CPGaZw9p_k8T_tcor-U/edit#heading=h.qt9rxydfd727)

### Related work

These have all be modified to support AF object or Valkyrie resource using the [established pattern](https://docs.google.com/document/d/1f9yDjtkXapFf1DYLyPhprnB4CPGaZw9p_k8T_tcor-U/edit#heading=h.qt9rxydfd727). 

* Issue #4101 Allow GrantEditToMembersJob to receive either an AF object or a Valkyrie resource as the Work (PR #4123)
* Issue #4102 Allow GrantReadToMembersJob to receive either an AF object or a Valkyrie resource as the Work (PR #4123)
* Issue #4103 Allow RevokeReadToMembersJob to receive either an AF object or a Valkyrie resource as the Work (PR #4123)
* Issue #4099 Add GlobalID::Identification for resources passed to jobs (PR #4124)

### PR DESCRIPTION
**Pull request by jeremyf**
## Backporting fix of logic around deleting nested membership

6f28a2fba144e2a8b426a585896575cbfc7c3f50

> When removing a collection after adding it to a work,
> CollectionsMembershipActor still adds the collection even though the
> _destroy flag is set to true.
>
> This is happening in both new/update works, in version 2.4.1, 2.7.0,
> and most likely 3.x.
>
> Steps to reproduce the past behavior
>
> 1.    Edit an existing work
> 2.    Add a collection to the work
> 3.    Remove the collection (before saving)
> 4.    Save the work

Based on this report, someone via the UI goes to a work, then chooses
to add a collection to the work. They then change their mind and mark
"delete" for that collection, then go to save. Prior to the logic that
is put in place, this would add the collection to the work.

The fix now prioritizes checking did someone say delete? If so, go
down that logic path else go down the add logic path.

Closes #4193

## Expanding backport of logic around deleting nested membership

21be50b9bf989c78d9b18a366c1dcf0effdbf5c8

In looking at a backport for #4193, I found similar logic in the
Hyrax::Actors::AttachMembersActor. I believe this is something that is
likely possible in the UI for work members.

Related to #4193 and #4278

## Renaming variable attach_members_actor

da7e8927ce58aec9cd1454162ead58f7b2a602cb

Renaming `little_boolean` to `boolean_type_caster`. As the originator
of the `little_boolean` variable name, I was aiming for playful. Yet
the name was a bit opaque. I believe the spirit of playfulness and
improved clarity of variable name shines through in
`boolean_type_caster`.

## Renaming variable for collections_membership_actor

10c0b738a3ee9b5271ae2b99fba37cb39a324d7b

Renaming `little_boolean` to `boolean_type_caster`. As the originator
of the `little_boolean` variable name, I was aiming for playful. Yet
the name was a bit opaque. I believe the spirit of playfulness and
improved clarity of variable name shines through in
`boolean_type_caster`.

Why did I not squash this into the previous commit ("Renaming variable
for attach_members_actor")? Because I am intending to cherry-pick one
of the commits to apply to master. The other commit, is not a problem
in master because that file has been refactored.

### CODE REVIEW

File: app/actors/hyrax/actors/attach_members_actor.rb [hunk 1]
```diff
@@ -30,10 +30,16 @@ def assign_nested_attributes_for_collection(env, attributes_collection)
           # checking for existing works to avoid rewriting/loading works that are
           # already attached
           existing_works = env.curation_concern.member_ids
+          little_boolean = ActiveModel::Type::Boolean.new
```
Comment (elrayle) [inline app/actors/hyrax/actors/attach_members_actor.rb:33]: Can you name this something like `boolean_type`?  The term little can mean small, but in this case, I assume you are using it as meaning lower_case.

**Comment by jeremyf** [comment]
@elrayle I've added an update as a third commit to the PR. Once agreed and merged, I'm going to cherry-pick that last commit and apply it to master (which has `little_boolean` in it).
