### PR TITLE
Valkyrize inherit_permissions_job

### LINKED ISSUE #4200: Allow InheritPermissionsJob to receive either an ActiveFedora object or a Valkyrie resource
### Descriptive summary
Convert InheritPermissionsJob to allow it to receive either an ActiveFedora based object or a Valkyrie::Resource equivalent object.

### Rationale
Allow jobs to execute correctly with existing AF implementation or the Wings Valkyrie implementation.

### Expected behavior
InheritPermissionsJob receives a Valkyrie::Resource and performs the action.

### Actual behavior
InheritPermissionsJob raises an exception when passed a Valkyrie::Resource.

### Approach for Conversion
[See Pattern for Jobs Receiving Parameter that may be an AF Object or a Valkyrie Resource](https://docs.google.com/document/d/1f9yDjtkXapFf1DYLyPhprnB4CPGaZw9p_k8T_tcor-U/edit#heading=h.qt9rxydfd727)

### Related work

These have all be modified to support AF object or Valkyrie resource using the [established pattern]((https://docs.google.com/document/d/1f9yDjtkXapFf1DYLyPhprnB4CPGaZw9p_k8T_tcor-U/edit#heading=h.qt9rxydfd727). 

* Issue #4101 Allow GrantEditToMembersJob to receive either an AF object or a Valkyrie resource as the Work (PR #4123)
* Issue #4102 Allow GrantReadToMembersJob to receive either an AF object or a Valkyrie resource as the Work (PR #4123)
* Issue #4103 Allow RevokeReadToMembersJob to receive either an AF object or a Valkyrie resource as the Work (PR #4123)
* Issue #4099 Add GlobalID::Identification for resources passed to jobs (PR #4124)

### PR DESCRIPTION
**Pull request by bkeese**
Fixes #4200 

Allows inherit_permissions_job to receive either an AF object or a Valkyrie resource as the Work

@samvera/hyrax-code-reviewers

### CODE REVIEW

File: app/jobs/inherit_permissions_job.rb [hunk 1]
```diff
@@ -4,21 +4,64 @@ class InheritPermissionsJob < Hyrax::ApplicationJob
   # Perform the copy from the work to the contained filesets
   #
   # @param work containing access level and filesets
-  def perform(work)
-    work.file_sets.each do |file|
-      attribute_map = work.permissions.map(&:to_hash)
+  # @param use_valkyrie [Boolean] whether to use valkyrie support
+  def perform(work, use_valkyrie: Hyrax.config.use_valkyrie?)
+    if use_valkyrie
+      work_permissions = permissions_map(work.permission_manager.acl.permissions)
```
Comment (jeremyf) [inline app/jobs/inherit_permissions_job.rb]: I like that you extracted the `af_perform` method. Would you be up for extracting a private method concerning `valkyrie_perform`?

Comment (bkeese) [reply app/jobs/inherit_permissions_job.rb]: :+1:  Done.

File: spec/jobs/inherit_permissions_job_spec.rb [hunk 2]
```diff
@@ -2,92 +2,199 @@
...
       end
+    end
+
+    context "when read groups change" do
+      let(:name) { 'my_read_group' }
+      let(:type) { 'group' }
+      let(:access) { 'read' }
 
       it 'copies permissions to its contained files' do
         # files have the depositor as the edit user to begin with
```
Comment (jeremyf) [inline spec/jobs/inherit_permissions_job_spec.rb]: This comment does not appear to match described line below.

File: spec/jobs/inherit_permissions_job_spec.rb [hunk 3]
```diff
@@ -2,92 +2,199 @@
...
-        file_set = work.file_sets.first
-        file_set.permissions.build(name: "remove_me", type: type, access: access)
-        file_set.save
+    context "when read people change" do
+      let(:name) { 'abc@123.com' }
+      let(:type) { 'person' }
+      let(:access) { 'read' }
+
+      it 'copies permissions to its contained files' do
+        # files have the depositor as the edit user to begin with
```
Comment (jeremyf) [inline spec/jobs/inherit_permissions_job_spec.rb]: This comment does not appear to match described line below.

File: spec/jobs/inherit_permissions_job_spec.rb [hunk 4]
```diff
@@ -2,92 +2,199 @@
...
-      # files have the depositor as the edit user to begin with
-      expect(work.file_sets.first.read_groups).to eq []
+        described_class.perform_now(resource, use_valkyrie: true)
 
-      described_class.perform_now(work)
-      work.reload.file_sets.each do |file|
-        expect(file.read_groups).to match_array ["my_read_group"]
-        expect(file.edit_users).to match_array [user.to_s]
+        # files have both edit users from parent resource
+        Hyrax.query_service.custom_queries.find_child_filesets(resource: resource).each do |file|
```
Comment (jeremyf) [inline spec/jobs/inherit_permissions_job_spec.rb]: In reading this spec, it would be possible that we have an empty array, which would mean the spec is not testing anything.

It may be helpful to capture the `Hyrax.query_service.custom_queries.find_child_filesets(resource: resource)` as a variable and say that you expect it to have a specific count/size.

File: spec/jobs/inherit_permissions_job_spec.rb [hunk 5]
```diff
@@ -2,92 +2,199 @@
...
+      let(:access) { 'read' }
 
       it 'copies permissions to its contained files' do
         # files have the depositor as the edit user to begin with
-        expect(work.file_sets.first.edit_users).to eq [user.to_s, "remove_me"]
+        expect(work.file_sets.first.read_groups).to eq []
 
-        described_class.perform_now(work)
+        described_class.perform_now(work, use_valkyrie: false)
         work.reload.file_sets.each do |file|
```
Comment (jeremyf) [inline spec/jobs/inherit_permissions_job_spec.rb]: In reading this spec, it would be possible that we have an empty array, which would mean the spec is not testing anything.

It may be helpful to capture the `Hyrax.query_service.custom_queries.find_child_filesets(resource: resource)` as a variable and say that you expect it to have a specific count/size.

File: spec/jobs/inherit_permissions_job_spec.rb [hunk 6]
```diff
@@ -2,92 +2,199 @@
...
+      it 'copies permissions to its contained files' do
+        # files have the depositor as the edit user to begin with
+        expect(work.file_sets.first.read_groups).to eq []
 
-      described_class.perform_now(work)
-      work.reload.file_sets.each do |file|
-        expect(file.read_users).to match_array ["abc@123.com"]
-        expect(file.edit_users).to match_array [user.to_s]
+        described_class.perform_now(work, use_valkyrie: false)
+        work.reload.file_sets.each do |file|
```
Comment (jeremyf) [inline spec/jobs/inherit_permissions_job_spec.rb]: In reading this spec, it would be possible that we have an empty array, which would mean the spec is not testing anything.

It may be helpful to capture the `Hyrax.query_service.custom_queries.find_child_filesets(resource: resource)` as a variable and say that you expect it to have a specific count/size.

File: spec/jobs/inherit_permissions_job_spec.rb [hunk 7]
```diff
@@ -2,92 +2,199 @@
...
+
+          # files have the depositor and extra user as the edit users to begin with
+          Hyrax.query_service.custom_queries.find_child_filesets(resource: resource).each do |file|
+            expect(file.edit_users).to match_array [user.to_s, user2.to_s]
+          end
+
+          described_class.perform_now(resource, use_valkyrie: true)
+
+          # files have single edit user from parent resource
+          Hyrax.query_service.custom_queries.find_child_filesets(resource: resource).each do |file|
```
Comment (jeremyf) [inline spec/jobs/inherit_permissions_job_spec.rb]: In reading this spec, it would be possible that we have an empty array, which would mean the spec is not testing anything.

It may be helpful to capture the `Hyrax.query_service.custom_queries.find_child_filesets(resource: resource)` as a variable and say that you expect it to have a specific count/size.

File: spec/jobs/inherit_permissions_job_spec.rb [hunk 8]
```diff
@@ -2,92 +2,199 @@
...
+
+        # files have no read users to begin with
+        Hyrax.query_service.custom_queries.find_child_filesets(resource: resource).each do |file|
+          expect(file.read_users.to_a).to be_empty
+        end
+
+        described_class.perform_now(resource, use_valkyrie: true)
+
+        # files have the extra user as the read user
+        Hyrax.query_service.custom_queries.find_child_filesets(resource: resource).each do |file|
```
Comment (jeremyf) [inline spec/jobs/inherit_permissions_job_spec.rb]: In reading this spec, it would be possible that we have an empty array, which would mean the spec is not testing anything.

It may be helpful to capture the `Hyrax.query_service.custom_queries.find_child_filesets(resource: resource)` as a variable and say that you expect it to have a specific count/size.

File: spec/jobs/inherit_permissions_job_spec.rb [hunk 9]
```diff
@@ -2,92 +2,199 @@
...
+      let(:group) { Hyrax::Group.new('my_read_group') }
+
+      it 'copies permissions to its contained files' do
+        resource.permission_manager.acl.grant(:read).to(group).save
+
+        # files have the depositor as the edit user to begin with
+        expect(resource.read_groups).to match_array ["my_read_group"]
+
+        described_class.perform_now(resource, use_valkyrie: true)
+        Hyrax.query_service.custom_queries.find_child_filesets(resource: resource).each do |file|
```
Comment (jeremyf) [inline spec/jobs/inherit_permissions_job_spec.rb]: In reading this spec, it would be possible that we have an empty array, which would mean the spec is not testing anything.

It may be helpful to capture the `Hyrax.query_service.custom_queries.find_child_filesets(resource: resource)` as a variable and say that you expect it to have a specific count/size.

File: spec/jobs/inherit_permissions_job_spec.rb [hunk 10]
```diff
@@ -2,92 +2,199 @@
...
+    context "when edit groups change" do
+      let(:group) { Hyrax::Group.new('my_edit_group') }
 
-    it 'copies permissions to its contained files' do
-      # files have the depositor as the edit user to begin with
-      expect(work.file_sets.first.read_groups).to eq []
+      it 'copies permissions to its contained files' do
+        resource.permission_manager.acl.grant(:edit).to(group).save
+
+        # files have the depositor as the edit user to begin with
```
Comment (jeremyf) [inline spec/jobs/inherit_permissions_job_spec.rb]: This comment does not appear to match described line below.

File: spec/jobs/inherit_permissions_job_spec.rb [hunk 11]
```diff
@@ -2,92 +2,199 @@
...
+        expect(resource.edit_groups).to match_array ["my_edit_group"]
 
-      described_class.perform_now(work)
-      work.reload.file_sets.each do |file|
-        expect(file.edit_groups).to match_array ["my_edit_group"]
-        expect(file.edit_users).to match_array [user.to_s]
+        described_class.perform_now(resource, use_valkyrie: true)
+        Hyrax.query_service.custom_queries.find_child_filesets(resource: resource).each do |file|
```
Comment (jeremyf) [inline spec/jobs/inherit_permissions_job_spec.rb]: In reading this spec, it would be possible that we have an empty array, which would mean the spec is not testing anything.

It may be helpful to capture the `Hyrax.query_service.custom_queries.find_child_filesets(resource: resource)` as a variable and say that you expect it to have a specific count/size.

**Comment by jeremyf** [comment]
I have a lot of "copy/paste" comments, but I also am very thankful for your contribution and PR. Good stuff to move us ever towards Valkyrie.

**Comment by bkeese** [comment]
Thank you @jeremyf. Good points. Fixed.

**Comment by bkeese** [comment]
OK. Now they're all fixed.

**Comment by jeremyf** [comment]
Woot! Now…why is CircleCI failing.
