### PR TITLE
make badge color configurable for collection types

### LINKED ISSUE #2707: Collection Types - create config to specify color to use for badges
### Descriptive summary

Collection type is displayed in the UI as a badge on index pages and show pages.  Currently, the badges are always green.  Add a configuration on the Description tab for the Collection Type where the user can specify the color to use for the badge.

### Rationale

UI components should be distinctive and configurable.

### Expected behavior

Each collection type should have a different color badge.
image

With user specified colors.

### Actual behavior

Each collection type has the same green color badge.
image

### New work for this issue

- [x] **DB Migration:** Add badge_color field to the collection type table to hold the badge color
- [x] **UI:** Add a field on Dashboard -> Settings -> Collection Types -> edit collection type -> Description tab to hold the selected color for the badge.  A widget to select the color is even better.
- [x] **UI/helper:** Update code where the badge is created to use the color in the badge_color field of the collection type. (e.g. Collection list in dashboard, Collection public and admin show pages)

NOTE: Current code uses the following to create the badge.
```
<span class="label label-success"><%= collection_presenter.collection_type_badge %></span>
```
Preferred code in the view is...
```
<%= collection_presenter.collection_type_badge %>  
```
The presenter will setup the badge with the correct styles.  

**Additional consideration:**  I believe that visibility uses a helper to create it's badges.  Then the same helper is used everywhere the visibility badge is used.  That is preferred, such that if the collection_presenter is used to create the badge, it is using the helper to really do the work.

### Steps to reproduce the behavior

1.  Dashboard --> Collections

Verify that each collection type has a different color badge that matches the color configured for its collection type (specified in Dashboard -> Settings -> Collection Types -> Edit collection type -> Description tab)

1.  Dashboard --> Collections -> click title of several collections

Verify that the collection type is a badge of the configured color.

1.  Dashboard --> Collections -> click title of a collection -> Public view of Collection

Verify that the collection type is a badge of the configured color.

### Related work

https://github.com/samvera/hyrax/pull/2659

### PR DESCRIPTION
**Pull request by blancoj**
Fixes #2707 ( eventually )

### CODE REVIEW

File: app/services/hyrax/collection_types/create_service.rb [hunk 1]
```diff
@@ -22,6 +22,7 @@ class CreateService
         require_membership: false,
         assigns_workflow: false,
         assigns_visibility: false,
+        badge_color: "#8b4513",
```
Comment (elrayle) [inline app/services/hyrax/collection_types/create_service.rb]: default: '#663333'

File: app/presenters/hyrax/collection_presenter.rb [hunk 2]
```diff
@@ -80,7 +81,7 @@ def total_viewable_collections
     end
 
     def collection_type_badge
-      collection_type.title
+      content_tag(:span, collection_type.title, class: "badge", style: "background-color: " + collection_type.badge_color + ";")
```
Comment (elrayle) [inline app/presenters/hyrax/collection_presenter.rb]: Can you use `class: 'label'` instead of badge?  That makes it make the style used by the visibility markers.
