### PR TITLE
Valkyrize Event Jobs

### LINKED ISSUE #4202: Allow ContentRestoredVersionEventJob to receive either an ActiveFedora object or a Valkyrie resource
### Descriptive summary
Convert ContentRestoredVersionEventJob to allow it to receive either an ActiveFedora based object or a Valkyrie::Resource equivalent object.

### Rationale
Allow jobs to execute correctly with existing AF implementation or the Wings Valkyrie implementation.

### Expected behavior
ContentRestoredVersionEventJob receives a Valkyrie::Resource and performs the action.

### Actual behavior
ContentRestoredVersionEventJob raises an exception when passed a Valkyrie::Resource.

### Approach for Conversion
[See Pattern for Jobs Receiving Parameter that may be an AF Object or a Valkyrie Resource](https://docs.google.com/document/d/1f9yDjtkXapFf1DYLyPhprnB4CPGaZw9p_k8T_tcor-U/edit#heading=h.qt9rxydfd727)

### Related work

These have all be modified to support AF object or Valkyrie resource using the [established pattern]((https://docs.google.com/document/d/1f9yDjtkXapFf1DYLyPhprnB4CPGaZw9p_k8T_tcor-U/edit#heading=h.qt9rxydfd727). 

* Issue #4101 Allow GrantEditToMembersJob to receive either an AF object or a Valkyrie resource as the Work (PR #4123)
* Issue #4102 Allow GrantReadToMembersJob to receive either an AF object or a Valkyrie resource as the Work (PR #4123)
* Issue #4103 Allow RevokeReadToMembersJob to receive either an AF object or a Valkyrie resource as the Work (PR #4123)
* Issue #4099 Add GlobalID::Identification for resources passed to jobs (PR #4124)

### PR DESCRIPTION
**Pull request by bkeese**
Fixes #4202, #4193, #4194 

Valkyrizes ContentRestoredVersionEventJob
Valkyrizes ContentUpdateEventJob
Valkyrizes ContentDepositorChangeEventJob

@samvera/hyrax-code-reviewers

### CODE REVIEW

File: app/models/concerns/hyrax/with_depositor.rb [hunk 1]
```diff
@@ -0,0 +1,11 @@
+module Hyrax::WithDepositor
+  # Adds metadata about the depositor to the asset and
+  # grants edit permissions to the +depositor+
+  # @param [String, #user_key] depositor
+  def apply_depositor_metadata(depositor)
```
Comment (no-reply) [inline app/models/concerns/hyrax/with_depositor.rb]: i think we should avoid putting this business logic into the model code. maybe the transaction step `SetUserAsDepositor` could be reused here?

File: spec/jobs/content_depositor_change_event_job_spec.rb [hunk 2]
```diff
@@ -14,15 +13,38 @@
...
-                                                .and change { another_user.events.length }.by(1)
-                                                                                          .and change { generic_work.events.length }.by(1)
+  context "when use_valkyrie is false" do
+    let(:generic_work) { create(:generic_work, title: ['BethsMac'], user: user) }
 
-    expect(user.profile_events.first).to eq(event)
-    expect(another_user.events.first).to eq(event)
-    expect(generic_work.events.first).to eq(event)
+    it "logs the event to the proxy depositor's profile, the depositor's dashboard, and the FileSet" do
+      expect do
```
Comment (no-reply) [inline spec/jobs/content_depositor_change_event_job_spec.rb]: could we clean this up? maybe something like

```ruby
expect { described_class.perform_now(generic_work, another_user) }
  .to change { user.profile_events.length }
  .by(1)
  .and change { another_user.events.length }
  .by(1)
  .and change { generic_work.events.length }
  .by(1)
```

File: spec/jobs/content_depositor_change_event_job_spec.rb [hunk 3]
```diff
@@ -14,15 +13,38 @@
...
+      expect(generic_work.events.first).to eq(event)
+    end
+  end
+
+  context "when use_valkyrie is true" do
+    let(:generic_work) { valkyrie_create(:hyrax_work, title: ['BethsMac']) }
+
+    it "logs the event to the proxy depositor's profile, the depositor's dashboard, and the FileSet" do
+      generic_work.apply_depositor_metadata(user)
+      allow_any_instance_of(described_class).to receive(:hyrax_test_simple_work_path).and_return("/concern/generic_works/#{generic_work.id}")
```
Comment (no-reply) [inline spec/jobs/content_depositor_change_event_job_spec.rb]: do we need `allow_any_instance_of`? if we're stubbing this (+0 to that---if it gets around the other issues here, i'm okay with it), could we stub it on the current instance and call `#perform` directly instead of routing through `.perform_now`?

File: app/models/hyrax/resource.rb [hunk 4]
```diff
@@ -32,6 +32,7 @@ module Hyrax
   #
   class Resource < Valkyrie::Resource
     include Hyrax::Naming
+    include Hyrax::WithEvents
```
Comment (jeremyf) [inline app/models/hyrax/resource.rb]: How does this interact with the pull request? I'm not seeing specs surrounding changes to Hyrax::Resource getting "with_events"

Comment (bkeese) [reply app/models/hyrax/resource.rb]: All of the event jobs rely on the ability to track and log those events for the affected resources. The Hyrax::WithEvents mixin adds that capability and is central to all of the specs for those jobs.

Comment (jeremyf) [reply app/models/hyrax/resource.rb]: The answer makes sense. My surprise came when I didn't see a change in spec to `hyrax/resource_spec.rb`

I'm wondering if there is a way to capture the expectation that Hyarx::Resource includes Hyrax::WithEvents. I know this relates to #4265 .

Comment (jeremyf) [reply app/models/hyrax/resource.rb]: I should add, that this is not a blocker for the PR. Just musing and wondering.

Comment (bkeese) [reply app/models/hyrax/resource.rb]: Interesting. I somehow missed the whole conversation around 4265. I'll look into adding something that directly tests the new event requirement for Hyrax::Resource.

**Comment by bkeese** [comment]
Bumping
