### PR TITLE
Hyrax-5471 - Works in mediated workflow not listed as managed works f…

### LINKED ISSUE #5471: Works in mediated workflow not listed as managed works for user with managing role
### Descriptive summary

Works in mediated workflow not listed as managed works on on a user's Dashboard Works page for users with managing role in an admin set with one-step mediated deposit workflow. These works are listed in the Review Submissions page. This occurs in HEAD.

### Rationale

This is an expected behavior.

### Expected behavior

Users with managing role for an admin set with a one-step mediated workflow should see a list of managed works on their Managed Works tab on their dashboard Managed Works page.

### Actual behavior

The Dashboard Managed Works tab does not display for users with a managing role in an admin set with one-step mediated deposit that have one or more member works.

### Steps to reproduce the behavior

1. Ensure that an admin set with a one-step mediated workflow exists.
2. As a normal user, create a work and add the admin set with a one-step mediated workflow identified or created in step 1.
3. Grant a non-admin user managing status to the admin set with the one-step mediated workflow used in step 2.
4. Go to the Dashboard, then Works page of a non-admin user with managing status from step 3.
5. The Managed User tab should be visible. Go to that tab.
6. The work created in step 2 should be listed in this tab. (It should also be listed in the Review Submissions tab.)

### Related work

New work under review not showing up at "Review Submissions" on dashboard #5436

### PR DESCRIPTION
**Pull request by fritzfreiheit**
Works in mediated workflow not listed as managed works for user with managing role

Fixes #5471

This issue stemmed from investigation into issue: #5436 

Add code to search builders to filter for admin sets with user's managing role.

Update [app/search_builders/hyrax/dashboard/managed_search_filters.rb] to add a method that performs the following steps:
* Find the managing sippity role
* convert the current user into a sippity agent
* from the agent's list of workflow responsibilities, find all responsibilities that are managing
* with this list of workflow responsibilities, find the corresponding admin set ids through the corresponding permission templates
* add a list of search filters that include "isPartOf" admin set ids identified in prior step

Guidance for testing, such as acceptance criteria or new user interface behaviors:
* (1) Ensure that an admin set with a one-step mediated workflow exists.
* (2) As a normal user, create a work and add the admin set with a one-step mediated workflow identified or created in step 1.
* (3) Grant a non-admin user managing status to the admin set with the one-step mediated workflow used in step 2.
* (4) Go to the Dashboard, then Works page of a non-admin user with managing status from step 3.
* (5) The Managed User tab should be visible. Go to that tab.
* (6) The work created in step 2 should be listed in this tab. (It should also be listed in the Review Submissions tab.)

@samvera/hyrax-code-reviewers

### CODE REVIEW

File: app/search_builders/hyrax/dashboard/managed_search_filters.rb [hunk 1]
```diff
@@ -11,15 +11,55 @@ def discovery_permissions
...
       end
+
+      # Look for a user's managing role and add filters for all admin sets that have permission
+      # templates that include managing roles.
+      #
+      # rubocop:disable Metrics/MethodLength
+      # rubocop:disable Metrics/PerceivedComplexity
+      # rubocop:disable Metrics/CyclomaticComplexity
+      def add_managing_role_search_filter(ability:, search_terms: [])
+        search_terms ||= []
```
Comment (dlpierce) [inline app/search_builders/hyrax/dashboard/managed_search_filters.rb:35]: Is setting `search_terms` again here needed? I think `search_terms` has a default value of [] from the arguments list a line above.

File: spec/search_builders/hyrax/dashboard/collections_search_builder_spec.rb [hunk 2]
```diff
@@ -55,6 +55,11 @@
 
     subject { builder.gated_discovery_filters }
 
+    before do
```
Comment (dlpierce) [inline spec/search_builders/hyrax/dashboard/collections_search_builder_spec.rb:58]: What problem is this addition addressing? This spec passes locally for me without manually saving the users.

File: app/search_builders/hyrax/dashboard/managed_search_filters.rb (hunk 1 above)
Comment (fritzfreiheit) [reply app/search_builders/hyrax/dashboard/managed_search_filters.rb:35]: I was covering the situation that nil was deliberately passed in as the value of :search_term. Does the default value block that possibility? I haven't actually tried that, but I'll test it locally.

File: spec/search_builders/hyrax/dashboard/collections_search_builder_spec.rb (hunk 2 above)
Comment (fritzfreiheit) [reply spec/search_builders/hyrax/dashboard/collections_search_builder_spec.rb:58]: I was getting the following error at the .to_sippity_agent line: Failure/Error: create_sipity_agent! ActiveRecord::RecordNotSaved: You cannot call create unless the parent is saved
I can take those saves out and retry it locally.

File: app/search_builders/hyrax/dashboard/managed_search_filters.rb (hunk 1 above)
Comment (fritzfreiheit) [reply app/search_builders/hyrax/dashboard/managed_search_filters.rb:35]: So ruby passes nil when a named parameter with a non-nil default is called:
`[1] pry(main)> def test_named_parm( parm: [] )
  puts parm.class.name
[1] pry(main)> def test_named_parm( parm: [] )
  puts parm.class.name
end
=> :test_named_parm
[2] pry(main)> test_named_parm
Array
=> nil
[3] pry(main)> test_named_parm( parm: nil )
NilClass
=> nil
`

**Review by dlpierce — APPROVED** [review]

**Comment by jlhardes** [comment]
This seems to be better for non-admin users with managing roles on mediated workflow admin sets. The admin user I can see on nurax-dev is still not seeing the full list of works in the Review Submissions section in the Under Review tab but the All Works tab shows a long list of works under review so this overall does seem to be an improvement. I am calling this a win and we'll see if there are other issues to figure out around the admin user view of mediated works.
