### PR TITLE
Universal viewer (UV) fails rendering png with transparent alpha channel

### LINKED ISSUE #3422: uv fails rendering png with transparent alpha channel
### Descriptive summary

Universal viewer (uv) fails rendering png with transparent alpha channel as well as uv download is providing corrupt jpg version 

### Expected behavior
uv should provide original png download link and render (if needed) jpg correctly

### Actual behavior
https://nurax-dev.curationexperts.com/concern/images/hd76s024f?locale=en#?c=0&m=0&s=0&cv=0&xywh=-2%2C0%2C290%2C99

### Steps to reproduce the behavior

1. https://nurax-dev.curationexperts.com/concern/images/hd76s024f?locale=en#?c=0&m=0&s=0&cv=0&xywh=-2%2C0%2C290%2C99Do this

### Related work

Link to related tickets or prior related work here.

### PR DESCRIPTION
**Pull request by geekscruff**
Fixes #3422; required a new version of Riiif: [#125](https://github.com/curationexperts/riiif/pull/125) released as 2.1.

This PR, combined with a change in Riiif will fix an issue whereby images with an alpha channel are incorrectly rendered by Universal Viewer backed by Riiif.

The incorrect rendering occurs because Riiif is asked for a 'jpg', and jpegs do not support alpha channels. 

One complication is that Universal Viewer requests 'jpg' even if png is specified in the manifest. The changes proposed in Riiif help to get around that by returning a png if an alpha channel present, irrespective of the request format.

Changes in Hyrax are:

1) Extend the characterize job to run Imagemagick identify and extract channel information (via the Riiif::ImageInfoExtractor) ... we need channel information to pass to Riiif, and we cannot get this from FITS AFAIK. Channel information could also be useful for preservation purposes, so it is useful to collect it. This channel information is added to the characterization_proxy and indexed into solr.

2) Change the Riiif info_service to return format AND alpha_channels; Riiif will then check for an alpha channel and preserve this, returning a png instead of a jpg.

@samvera/hyrax-code-reviewers

### CODE REVIEW

**Comment by cjcolvar** [comment]
I wonder if it will become a problem having this property called "channels" when audio files have "channels" as well.
https://github.com/samvera/hydra-works/blob/master/lib/hydra/works/characterization/schema/audio_schema.rb#L4

**Comment by geekscruff** [comment]
@cjcolvar good point, I'll rename it alphachannels ... I want to get this finished this week if at all possible

**Comment by cjcolvar** [comment]
It would be good for someone else to review this because I don't work with images and don't feel confident enough.

**Comment by geekscruff** [comment]
@cjcolvar thanks! I need to get the tests passing, and do a bit of manual QA of my own, then I'll ping a couple of reviewers

**Comment by geekscruff** [comment]
@no-reply Hi Tom, any chance of a review?

File: app/jobs/characterize_job.rb [hunk 1]
```diff
@@ -9,11 +9,26 @@ class CharacterizeJob < Hyrax::ApplicationJob
...
+      Hydra::Works::CharacterizationService.run(file_set.characterization_proxy, filepath)
+      Rails.logger.debug "Ran characterization on #{file_set.characterization_proxy.id} (#{file_set.characterization_proxy.mime_type})"
+      file_set.characterization_proxy.alpha_channels = channels(filepath) if file_set.image? && Hyrax.config.iiif_image_server?
+      file_set.characterization_proxy.save!
+      file_set.update_index
+      file_set.parent&.in_collections&.each(&:update_index)
+    end
+
+    def channels(filepath)
+      ch = Riiif::ImageMagickInfoExtractor.new(filepath).extract[:channels]
```
Comment (cjcolvar) [inline app/jobs/characterize_job.rb]: Maybe it makes sense to avoid the dependency on Riiif and instead pull this code into Hyrax or where ever characterization code lives.

File: app/presenters/hyrax/displays_image.rb [hunk 2]
```diff
@@ -35,5 +37,9 @@ def iiif_endpoint(file_id)
           profile: Hyrax.config.iiif_image_compliance_level_uri
         )
       end
+
+      def image_format(channels)
+        channels.find { |c| c.include?('rgba') }.nil? ? 'jpg' : 'png'
```
Comment (cjcolvar) [inline app/presenters/hyrax/displays_image.rb]: It looks like this will always return a jpg or png but do other IIIF image servers or IIIF clients make use of or expect anything different?  Maybe not.

Comment (dlpierce) [reply app/presenters/hyrax/displays_image.rb]: jpg is the only format required at all compliance levels, with png required for level 2. See https://iiif.io/api/image/2.1/compliance/#format

File: lib/generators/hyrax/riiif_generator.rb [hunk 3]
```diff
@@ -33,7 +33,7 @@ def mount_route
 
   def override_image_url_builder_in_hyrax_config
     insert_into_file 'config/initializers/hyrax.rb', before: /^  # config.iiif_image_url_builder/ do
-      "  config.iiif_image_url_builder = lambda do |file_id, base_url, size|\n" \
+      "  config.iiif_image_url_builder = lambda do |file_id, base_url, size, format|\n" \
```
Comment (cjcolvar) [inline lib/generators/hyrax/riiif_generator.rb]: Does this change in the lambda signature require updating documentation or at least need to be called out in the 3.0 migration docs?

Comment (dlpierce) [reply lib/generators/hyrax/riiif_generator.rb]: Yes, I believe it will.
