### PR TITLE
Asynchronous IngestJob and JobIoWrapper

### LINKED ISSUE #1239: Callback timing broken w/ asynchronous jobs
Here we have a method, `update_content`: https://github.com/samvera/hyrax/blob/master/app/actors/hyrax/actors/file_set_actor.rb#L74-L78
It calls `ingest_file` w/ async set true, tossing a job in the queue…. but it immediately calls the callback.
```ruby
      def update_content(file, relation = 'original_file')
        build_file_actor(relation).ingest_file(file, true)
        Hyrax.config.callback.run(:after_update_content, file_set, user)
        true
      end
```
That boolean was changed by @mjgiarlo 2 months ago. The problem is that in realistic scenarios, `Hyrax.config.callback.run(:after_update_content, file_set, user)` happens BEFORE the update.  By toggling it async, the logical relationship between itself and callback was broken.  Also exposed #1155 and https://github.com/samvera-labs/hyku/issues/1182.  

What do we want to do?

1. switch back to synchronous.  Princeton/PSU has been saying “we must retain async”, so that seems out.
2. remove callback
3. replace it w/ different callback from inside the new ingest job

The latter has the advantage of also covering `create_content` (not just `update_content`)… which otherwise doesn’t seem to get a callback, despite being more common and presumably more important.  Depending on what actions are expected in the callbacks, it makes more sense for them to execute in the same thread as the job... or the opposite.  If you are adding a user-notification to flash in the page response, for example, it does nothing from the job context on a worker box.

But, the only way to allow async and a logical `after` is to tie to the job, not the invocation.  Otherwise you risk retrieving and operating on (say, building a secondary index) with the un-updated object.  Note: you don't get another chance later, you just get the wrong object.  I think this is universally unacceptable.

### PR DESCRIPTION
**Pull request by atz**
Fixes #1239 
Follows #1206 

`IngestJob` replaces the removed `IngestFileJob`, and is wired in for asynchronous use as before.

`JobIoWrapper` is persistence-backed, allowing it to be passed to asynchronous jobs.

In actors, where async job is spawned, return it (instead of `true`), in case caller wants to wait for completion or otherwise track/reference it. This also signifies the difference between "action successfully completed" like from `.save` and "a deferred thing will determine success/failure".

Replace one-off `after_update_content` callback with `after_perform` block.  Otherwise, the callback can happen **before** the async event.

In general, I propose that the rails framework callbacks (especially on ActiveJob) are a universally better approach than our bespoke magic in `config/initializers/hyrax_callbacks.rb`, giving us:
- `before` callbacks, symmetric to each `after` callback
- `around` callbacks, combining `before` and `after` actions
- a complete range of other callbacks
- the ability to use asynchronicity without breaking timing logic

If the problem is that some job callers want the callback to be optional while others do not, see the implementation of `:notification` in `IngestJob`'s `after_perform` block for an example that handles that.

TODO:
- update downstream jobs to accept `JobIoWrapper` for completeness
- update last two jobs using `Hyrax::WorkingDirectory` and remove it

### CODE REVIEW

File: app/actors/hyrax/actors/file_set_actor.rb [hunk 1]
```diff
@@ -143,36 +157,10 @@ def label_for(file)
           end
         end
 
-        # Takes an optional block and executes the block if the save was successful.
-        # @return [Boolean] false if the save was unsuccessful
-        def save
```
Comment (atz) [inline app/actors/hyrax/actors/file_set_actor.rb]: Removed this unused weirdo method.

**Comment by atz** [comment]
@tpendragon, @escowles: I think this accomplishes what we wanted.

**Comment by atz** [comment]
Weird.  I don't understand how Travis can get this error that I don't get locally:
```
Failure/Error: expect { described_class.create!(file_set_id: file_set_id, path: path) }.to raise_error ActiveRecord::RecordInvalid
       expected ActiveRecord::RecordInvalid but nothing was raised
```
The model has:
```
belongs_to :user
```

`belongs_to` is a [default required relationship](http://blog.bigbinary.com/2016/02/15/rails-5-makes-belong-to-association-required-by-default.html) in rails 5+, and the version of rails is [5.0.4](https://travis-ci.org/samvera/hyrax/jobs/246863681#L725).  Therefore, `user` is required.  So how can `described_class.create!(file_set_id: file_set_id, path: path)` succeed?  Only on Travis?

**Comment by escowles** [comment]
@atz I'm not sure I understand exactly what's going on here — this is modeling the uploaded file in ActiveRecord, so it can be serialized/deserialized by an ActiveJob?  If so, then the shared filesystem requirement is still there.

The benefit then, is that the ActiveRecord object can be used to figure out when the background job has been run, as opposed to simply passing the local filename (where you would have no way of knowing if it was safe to remove the temp file).

Assuming I'm understanding this correctly, that seems like a nice improvement.

**Comment by atz** [comment]
@escowles: Yes, serialization is indispensable.  The model also allows `#read` (and `#size`) to use either a File opened on the provided pathname or a referenced `Hyrax::UploadedFile`.  This is basically similar to what `Hyrax::WorkingDirectory` was trying to do, but starting from the data and reducing the complexity of arguments/logic inside the job.

**Comment by atz** [comment]
Also the main point is this gets back async at the top level of ingest (`IngestJob.perform_later` instead of inline).

**Comment by atz** [comment]
@escowles Added some additional testing to make that flexibility more obvious.  Let me know if you have any questions.

**Comment by mjgiarlo** [comment]
@atz I see two TODOs listed in the description above. Are these coming in this PR, or do you see them as follow-up work?

**Comment by mjgiarlo** [comment]
@atz If we wanted to test this branch in Hyku (deployed in AWS0, would we need to make any changes at that layer? Or should it work in that environment?

**Comment by atz** [comment]
@mjgiarlo That's follow-on work.  No known problems w/ Hyku (but written and tested exclusively at Hyrax level).

File: app/models/job_io_wrapper.rb [hunk 2]
```diff
@@ -0,0 +1,79 @@
...
+# for the metadata that might travel w/ the actor's various supported types of @file.
+# For example, we cannot just do:
+#
+#   SomeJob.perform_later(arg1, arg2, File.new('/path/to/file'))
+#
+# Because we'll get:
+#
+#   ActiveJob::SerializationError: Unsupported argument type: File
+#
+# This also applies to Hydra::Derivatives::IoDecorator, Tempfile, etc., pretty much any IO.
```
Comment (jcoyne) [inline app/models/job_io_wrapper.rb]: How could this apply to a Tempfile?  That would be removed as soon as the process ended, right?

File: app/actors/hyrax/actors/file_set_actor.rb [hunk 3]
```diff
@@ -10,6 +10,40 @@ def initialize(file_set, user)
         @user = user
       end
 
+      # @!group Asynchronous Operations
+
+      # Spawns asynchronous IngestJob
+      # Called from FileSetsController, AttachFilesToWorkJob, ImportURLJob, IngestLocalFileJob
+      # @param [Hyrax::UploadedFile, File, ActionDigest::HTTP::UploadedFile, Tempfile] file the file uploaded by the user
```
Comment (jcoyne) [inline app/actors/hyrax/actors/file_set_actor.rb]: You can't accept Tempfile here. Because you can't run an asynchronous job on a file that is temporary.

File: spec/actors/hyrax/actors/file_set_actor_spec.rb [hunk 4]
```diff
@@ -223,80 +247,6 @@
...
-    context "when file set params with visibility are specified with strings as keys" do
-      let(:file_set_params) { { "visibility" => Hydra::AccessControls::AccessRight::VISIBILITY_TEXT_VALUE_PUBLIC } }
-
-      it "does need to assign visibility" do
-        expect(actor.send(:assign_visibility?, file_set_params)).to eq true
-      end
-    end
-  end
-
-  describe "#set_representative" do
```
Comment (jcoyne) [inline spec/actors/hyrax/actors/file_set_actor_spec.rb]: Why was this test coverage removed? Previously we covered thumbnail set and unset. By removing this method, which was unnecessary to acchieving the JobIoWrapper, you've made the code less testable.  I'd like to see these tests and their methods restored.

**Comment by mjgiarlo** [comment]
@atz I tested this branch in Hyku, specifically the docker-compose instance, and uploaded files never seemed to get attached. I didn't have enough time to troubleshoot, so I pushed this up for further poking: https://github.com/samvera-labs/hyku/pull/1303

**Comment by atz** [comment]
@mjgiarlo: that is also a complaint about the *current* Hyrax code.

File: spec/actors/hyrax/actors/file_set_actor_spec.rb (hunk 4 above)
Comment (atz) [inline spec/actors/hyrax/actors/file_set_actor_spec.rb]: The functionality is still tested.  Expecting a one-line like:
```ruby
work.thumbnail = file_set if work.thumbnail_id.blank?
``` 
to require its own broken out test coverage is **absurd**.

**Comment by mjgiarlo** [comment]
@atz Yeah, that's true. We pointed Hyku at a Hyrax commit before #1206 landed so the demo instance works for folks: https://github.com/samvera-labs/hyku/pull/1292 I was testing the hypothesis that this PR would get Hyrax working for Hyku again, and that's not yet the case.

File: app/actors/hyrax/actors/file_set_actor.rb (hunk 3 above)
Comment (atz) [inline app/actors/hyrax/actors/file_set_actor.rb]: That's what `wrapper!` is for.  It's the point of this PR.  We can accept `Tempfile` here, because this is not the job.  We pass the non-temp `JobIoWrapper` object to the job.

File: app/models/job_io_wrapper.rb (hunk 2 above)
Comment (atz) [inline app/models/job_io_wrapper.rb]: This identifies that `Tempfile` (and other IO classes) cannot be serialized for a job, let alone deserialized in another process.

**Comment by atz** [comment]
Rebased and re-rubocopped.  

From all the folks who cared strongly about having an async top-level ingest job a week ago, I might expect more review attention here, since this is what delivers it.

**Comment by mjgiarlo** [comment]
@atz I'm going to take this for a test-drive today. Thanks for yr patience, sir.

**Comment by mjgiarlo** [comment]
@atz I want to correct my last comment on this PR. Namely:

> With samvera-labs/hyku#1303, I was testing the hypothesis that this branch would get Hyrax working in Hyku again, and that's not yet the case.

This was incorrect -- while I did point Hyku at the branch for this PR, I failed to notice that I needed to generate and load a new Hyrax database migration. When I did that, this PR restored the ability to attach files in Hyku. Thanks for this work, @atz, and apologies for the misunderstanding I caused earlier.

**Comment by jcoyne** [comment]
@atz my concern here is that you are changing code that does not need to be changed to accomplish the goal of this PR. Someone submitted this code (@val99erie) in it's current format and it went through review.  They probably had a reason for writing it that way and defended it in the review.  So it's disrespectful of their efforts to just change it without a reason.  If you feel that change is important to make, please break it into a different pull request and submit it with you reason for changing it.

File: app/actors/hyrax/actors/file_set_actor.rb (hunk 1 above)
Comment (mjgiarlo) [inline app/actors/hyrax/actors/file_set_actor.rb]: AFAIK, this code is nearly five years old to the day: https://github.com/samvera/sufia/commit/530868950a314e4dfdd78f2f02c262636bc70129#diff-47b795ef43d49d2d98f2e4a700c306b5R163

I'm not sure we still need it.

Comment (mjgiarlo) [inline app/actors/hyrax/actors/file_set_actor.rb]: Can you also remove the dependency on `retriable` from the gemspec? This was the only code that used that gem, AFAIK, so now that it's gone we no longer need the dependency.

**Comment by atz** [comment]
I think the code was unnecessarily indirect and would have gladly objected at that time.  Even if it was defensible then on some premise, I don't think it is now.  I also removed an unused method, for which the same arguments about provenance, precedence and previous intent could be made.  

@val99erie is free to offer comment here, if it is considered important/defensible, and I would certainly consider the author's position on any given code with unique interest (but it has been 11 days already, I won't wait forever).  Broadly, it isn't disrespectful to maintain and improve others work, and much of the value of private methods is that they allow for seemless refactoring or removal.  On the other hand, it is disrespectful to hold up diligent and material work over hypothetical stylistic concerns offered by proxy, in my opinion.  The problem is not that we lack deference to legacy code, but much the opposite.  

@jcoyne Do you personally think it is important to atomically test (what is effectively) individual lines of code?  Or just that since somebody once thought it was wise, we should stick to that indefinitely?  The cleanup was useful to me in understanding what I needed to understand to accomplish and test this PR.  Its inclusion is not arbitrary.  As its author, I can tell you the "goal of this PR" includes **many** improvements to structure, reliability, documentation, testing and logic, including that cleanup.

File: app/controllers/hyrax/file_sets_controller.rb [hunk 5]
```diff
@@ -254,12 +225,6 @@ def empty_file?(file)
         (file.respond_to?(:tempfile) && file.tempfile.size == 0) || (file.respond_to?(:size) && file.size == 0)
       end
 
-      # this is provided so that implementing application can override this behavior and map params to different attributes
```
Comment (mjgiarlo) [inline app/controllers/hyrax/file_sets_controller.rb]: Do we think that the need expressed in this comment is no longer around? This ability to override the controller has been around for a long time, since https://github.com/samvera/sufia/commit/92a3788ec799183e862e1a636cdabebf305e5374.

File: app/jobs/ingest_job.rb [hunk 6]
```diff
@@ -0,0 +1,17 @@
+class IngestJob < Hyrax::ApplicationJob
+  queue_as Hyrax.config.ingest_queue_name
+
+  after_perform do |job|
+    opts = job.arguments.reverse.detect { |x| x.is_a? Hash } || {}
```
Comment (mjgiarlo) [inline app/jobs/ingest_job.rb]: Why is the `#reverse` needed here?

File: app/jobs/ingest_job.rb [hunk 7]
```diff
@@ -0,0 +1,17 @@
...
+    wrapper = job.arguments.first
+    ContentNewVersionEventJob.perform_later(wrapper.file_set, wrapper.user) if opts[:notification]
```
Comment (mjgiarlo) [inline app/jobs/ingest_job.rb]: I'm not sure what a better approach would look like, but I'm wondering if this line will get us into trouble later because of where and when this coupling is expressed. For instance, a downstream app may want to add notifications with other jobs, but we don't want to assume all jobs with `notification: true` correspond to new version events. The callbacks used before -- though invoked at the incorrect time 'til this PR -- had the advantage of giving us more flexibility, which could be overridden by downstream consumers. Can you suggest an improvement here? FWIW, I wouldn't block the PR over this, but I would like to ticket this for follow-on work.

File: app/models/job_io_wrapper.rb [hunk 8]
```diff
@@ -0,0 +1,79 @@
...
+  def mime_type
+    super || extracted_mime_type
+  end
+
+  def file_set
+    FileSet.find(file_set_id)
+  end
+
+  def file_actor
+    Hyrax::Actors::FileActor.new(file_set, relation.to_sym, user)
```
Comment (mjgiarlo) [inline app/models/job_io_wrapper.rb]: Can/ought this be private too?

File: app/jobs/ingest_job.rb (hunk 6 above)
Comment (atz) [inline app/jobs/ingest_job.rb]: We want the "lastmost hash", if any.  In this case is isn't particularly important, now that the number of arguments is small (1-2), but it minimizes the number of times the `detect` block is evaluated (max once).

File: spec/actors/hyrax/actors/file_actor_spec.rb [hunk 9]
```diff
@@ -34,7 +34,7 @@ class FileSetWithExtras < FileSet
     end
     it 'uses the relation from the actor' do
       expect(CharacterizeJob).to receive(:perform_later).with(file_set, String, io.tempfile.path)
-      expect(actor.ingest_file(io)).to be_truthy
+      actor.ingest_file(io)
```
Comment (mjgiarlo) [inline spec/actors/hyrax/actors/file_actor_spec.rb]: Do we expect this to at least not return `false` here, or do the tests on the preceding and succeeding lines suffice? (I suspect the latter, that if the `CharacterizeJob` is called successfully and the reloaded mime type is as we expect it, we no longer need to check the return value of `#ingest_file`.)

File: app/models/job_io_wrapper.rb (hunk 8 above)
Comment (atz) [inline app/models/job_io_wrapper.rb]: I considered that, but other jobs receiving `JobIoWrapper` objects are going to act directly via this `file_actor`.  The only reason it isn't currently directly invoked is the convenience method for `ingest_file`.  All _other_ actions (via the actor) would invoke `file_actor` or require their own convenience method.  I didn't want to preclude any methods in the actor from being used in jobs or force jobs to manually reinstantiate their own file actor.

File: spec/actors/hyrax/actors/file_set_actor_spec.rb [hunk 10]
```diff
@@ -25,17 +71,9 @@
...
-      # NOTE: we have to use this unweidly block instead of `.with(io)`
-      # because Hydra::Derivatives::IoDecorator objects cannot be compared
-      # https://github.com/samvera/hydra-derivatives/issues/165
-      # We reuse this pattern throughout this file.
-      # TODO: replace IoDecorator with a regular Hyrax::Io class
-      expect(file_actor).to receive(:ingest_file) do |input|
-        expect(input.mime_type).to eq(uploaded_file.content_type)
-        expect(input.original_name).to eq(uploaded_file.original_filename)
-      end
+      # expect(actor).to receive(:wrapper).with(file, relation)
```
Comment (mjgiarlo) [inline spec/actors/hyrax/actors/file_set_actor_spec.rb]: Can this comment be removed?

**Comment by jcoyne** [comment]
@atz I don't think line coverage is important. However, I believe that we ought to cover all the interesting scenarios (with a thumbnail, without one, with a representative and without).  Testing this when the logic all in one method is pretty difficult.  I find that it is easier to expect that `set_thumbnail` and `set_representative` are invoked in one tests, and then test their variant behavior in other tests.

File: spec/actors/hyrax/actors/file_set_actor_spec.rb [hunk 11]
```diff
@@ -227,80 +254,6 @@
     end
   end
 
-  describe "#assign_visibility?" do
```
Comment (mjgiarlo) [inline spec/actors/hyrax/actors/file_set_actor_spec.rb]: Why'd you remove the `#assign_visibility?` block of tests? It doesn't look like you touched this method's implementation.

Comment (mjgiarlo) [inline spec/actors/hyrax/actors/file_set_actor_spec.rb]: Nevermind, I now see these tests moved here: https://github.com/samvera/hyrax/pull/1301/files#diff-1950b382cdd95aed6b463a2f079106cdR52 Right?

File: spec/actors/hyrax/actors/file_set_actor_spec.rb (hunk 4 above)
Comment (mjgiarlo) [inline spec/actors/hyrax/actors/file_set_actor_spec.rb]: @atz Can you point me at where this is still tested?

File: app/actors/hyrax/actors/file_set_actor.rb (hunk 1 above)
Comment (atz) [inline app/actors/hyrax/actors/file_set_actor.rb]: I'd be happy to attempt that.

File: app/jobs/ingest_job.rb (hunk 6 above)
Comment (mjgiarlo) [inline app/jobs/ingest_job.rb]: @atz OK. Could you add that as a comment above this line? That's helpful to know.

File: app/jobs/ingest_job.rb [hunk 12]
```diff
@@ -0,0 +1,17 @@
...
+  end
+
+  # @param [JobIoWrapper] wrapper
+  # @param [Boolean] notification send the user a notification, used in after_perform callback
+  # @see 'config/initializers/hyrax_callbacks.rb'
+  # rubocop:disable Lint/UnusedMethodArgument
```
Comment (mjgiarlo) [inline app/jobs/ingest_job.rb]: Do we need to re-enable this rule after line 16, or will Rubocop do the right thing? I'd prefer to be explicit here, but don't care *too* much.

File: app/models/job_io_wrapper.rb (hunk 8 above)
Comment (mjgiarlo) [inline app/models/job_io_wrapper.rb]: K, works for me, @atz.

File: app/controllers/hyrax/file_sets_controller.rb (hunk 5 above)
Comment (atz) [inline app/controllers/hyrax/file_sets_controller.rb]: This description, the method name and the method content seem unrelated to each other.  It being a private method means it is **not** part of the public contract of the class, regardless of the comment's claim.  The approach that says (several times over in this class) "override this private method" is a fundamental OO error we should avoid.  Basic OO approaches or well-known Rails callbacks would be appropriate directions for Hyrax to point users towards instead of overriding private methods.

Comment (mjgiarlo) [inline app/controllers/hyrax/file_sets_controller.rb]: They may seem unrelated, but I believe they're being used by folks to make overrides such as:

* https://github.com/duke-libraries/course-assets/blob/2c8a64687649eb2ebc8cf6777edf270ada1e3ed2/lib/course_assets/files_controller_behavior.rb#L5-L7
* https://github.com/ualbertalib/HydraNorth/blob/d4a1c87cf34e376f69138c411cc21819f1edb2f2/app/controllers/concerns/hydranorth/files_controller_behavior.rb#L61-L65
* https://github.com/ihrnexuslab/research-repo/blob/572865c2125c18891762abaa0efdeb2d9895da7d/app/controllers/generic_files_controller.rb#L121-L132
* https://github.com/sephirothkod/Sufia-Head/blob/7994b6eb6eeb29ac40b3d243af8f65bc07d43947/app/controllers/concerns/sufia/files_controller_behavior.rb#L286-L297

Given that folks are still using this seam, and it's not necessary for this PR (methinks?), would you consider reverting this change?

File: app/jobs/ingest_job.rb (hunk 7 above)
Comment (atz) [inline app/jobs/ingest_job.rb]: It wasn't more flexibility at all.  `ActiveJob` callbacks are *far* more flexible than our one-offs **and actually work** without logical errors.  We had `before` callbacks with no symmetric `after`.  We don't provide matching `around` callbacks.  Rails has already worked this stuff out to a vast degree, and already has symmetric and complete before/after/around hooks.  In the context of jobs, I don't see our one-off callbacks as ever preferable.  

But there are various approaches to this that I considered (some, even implemented) before this proposed one that might be useful to restate:
- separate jobs: `IngestJob` and `IngestJobWithNotification`.  The latter extends the former and unilaterally applies the `after_perform` block.  PRO: options fall away.  CON: would need a descendant job for each existing job.  If a second (or more) such runtime option emerged, it would become a nonsensical matrix of classes, like `IngestJobWithBellsWithNotification` and `IngestJobWithBellsWithWhistlesWithNotification`
- some refinement, where the `after_perform` block moves into a base class (or even the main `Hyrax::ActiveJob` class).  I would consider implementing this when a second job adopts the same pattern, not before.
- adding to `JobIoWrapper`: did not pursue this because it seemed distinct from the local filesystem problem the class intends to solve.  The *same* `JobIoWrapper` (uploaded file) might be expected to be passed to a series of jobs, some of them with notifications, some without.  We shouldn't affect the persisted representation of the wrapper just to reflect that.  Indeed we CANNOT, if a given job wants to invoke two separate `perform_later`s, it would be, e.g.: 
```
Job1.perform_later(wrapper)
wrapper.notification = false
wrapper.save
Job2.perform_later(wrapper)
```
But given that we don't know when the jobs process, i.e. when the persisted wrapper is retrieved from DB, this will allow `Job1` to retrieve the state we intended for `Job2`.

File: app/controllers/hyrax/file_sets_controller.rb (hunk 5 above)
Comment (atz) [inline app/controllers/hyrax/file_sets_controller.rb]: Not really.  It's fundamentally bad form and I cannot support it.  If you want, I would remove ALL other references to overriding private methods.  I would *consider* someone else's PR to make all such methods `public`, but only with significant skepticism given how scattershot they seem to be.  

We are trying to be **better** than sufia.  Keeping people dependent on hacks is not doing them any favors.

File: spec/actors/hyrax/actors/file_actor_spec.rb (hunk 9 above)
Comment (atz) [inline spec/actors/hyrax/actors/file_actor_spec.rb]: Right, doesn't matter much and we get into circular (not particularly informative) testing logic.  `CharacterizeJob.perform_later` is the last thing in the method.  We don't actually want that job to execute here, and we want to be sure it gets called, so we have an `expect` catch that.  At that point, we have assumed control of what the "return value" would be, so testing for it would be unnecessary.

File: app/jobs/ingest_job.rb (hunk 12 above)
Comment (atz) [inline app/jobs/ingest_job.rb]: No, it only affects this file, which is now so terse as to only include 1 method.

File: spec/actors/hyrax/actors/file_set_actor_spec.rb (hunk 11 above)
Comment (atz) [inline spec/actors/hyrax/actors/file_set_actor_spec.rb]: Right, I grouped all the private methods being tested together in the spec.

File: spec/actors/hyrax/actors/file_set_actor_spec.rb (hunk 10 above)
Comment (atz) [inline spec/actors/hyrax/actors/file_set_actor_spec.rb]: ok

File: app/controllers/hyrax/file_sets_controller.rb (hunk 5 above)
Comment (mjgiarlo) [inline app/controllers/hyrax/file_sets_controller.rb]: I don't disagree with any of that, @atz, but I wonder how removing the code in question helps this PR.

Or maybe we're not as concerned with this specific override capability in Hyrax as we were in Sufia? Thoughts welcome from @jcoyne, the original author of this method.

File: app/jobs/ingest_job.rb (hunk 7 above)
Comment (mjgiarlo) [inline app/jobs/ingest_job.rb]: @atz :speech_balloon: 
> separate jobs: IngestJob and IngestJobWithNotification. The latter extends the former and unilaterally applies the after_perform block. PRO: options fall away. CON: would need a descendant job for each existing job. If a second (or more) such runtime option emerged, it would become a nonsensical matrix of classes, like IngestJobWithBellsWithNotification and IngestJobWithBellsWithWhistlesWithNotification

Yeah, :-1: 

> some refinement, where the after_perform block moves into a base class (or even the main Hyrax::ActiveJob class). I would consider implementing this when a second job adopts the same pattern, not before.

:+1: to the "after, not before" comment. Now's not the right time for that.

> adding to JobIoWrapper: did not pursue this because it seemed distinct from the local filesystem problem the class intends to solve. The same JobIoWrapper (uploaded file) might be expected to be passed to a series of jobs, some of them with notifications, some without. We shouldn't affect the persisted representation of the wrapper just to reflect that.

OK. What about adding an arg to, or changing the second arg in, `IngestJob` to allow consumers to inject a notification class or the like? That way the code could look like:

```ruby
IngestJob.perform_later(wrapper, notification: true, notification_class: ContentNewVersionEvent)
```

Though maybe we'd need to pass that as a string rather than class name, and the complicating factor here is that event jobs don't all receive the same arguments, so we'd need some way to deal with that. Thinking aloud here.

File: spec/actors/hyrax/actors/file_actor_spec.rb (hunk 9 above)
Comment (mjgiarlo) [inline spec/actors/hyrax/actors/file_actor_spec.rb]: WFM. :+1:

File: spec/actors/hyrax/actors/file_set_actor_spec.rb (hunk 10 above)
Comment (mjgiarlo) [inline spec/actors/hyrax/actors/file_set_actor_spec.rb]: :cool:

File: spec/actors/hyrax/actors/file_set_actor_spec.rb (hunk 11 above)
Comment (mjgiarlo) [inline spec/actors/hyrax/actors/file_set_actor_spec.rb]: Nice. :beers:

File: app/jobs/ingest_job.rb (hunk 12 above)
Comment (mjgiarlo) [inline app/jobs/ingest_job.rb]: K.

File: app/jobs/ingest_job.rb (hunk 6 above)
Comment (atz) [inline app/jobs/ingest_job.rb]: I'm not sure what you're asking for.  `We want the lastmost hash`?

File: app/jobs/ingest_job.rb (hunk 7 above)
Comment (atz) [inline app/jobs/ingest_job.rb]: Correct, event jobs do not take the same args or the same number of args.  That latter idea sounds like making the thing you're objecting to worse, no?  Also the caller doesn't get to decide what *type* of action this job considers itself to implement.  If we wanted to go that way (I don't), we would cut out the boolean, and just use the presence of a `notification_class` to signal `true`.

File: app/controllers/hyrax/file_sets_controller.rb (hunk 5 above)
Comment (atz) [inline app/controllers/hyrax/file_sets_controller.rb]: I'm sick of dancing around completely busted patterns that are somehow still regarded as sacred.  It is funny because normally in this situation, legacy status quo folks will argue "we need a deprecation warning!".   But that reveals how messed up this situation is, since **you don't get deprecation warnings for private methods**!  IF this hack is important to somebody, it is on them to provide an implementation here that is not an abomination.  We move them in the right direction by removing it (and the rest).

File: spec/actors/hyrax/actors/file_set_actor_spec.rb (hunk 4 above)
Comment (atz) [inline spec/actors/hyrax/actors/file_set_actor_spec.rb]: It was in integrations.  But for ease of mind over what is, effectively, two lines of code and to get away from overuse of integration testing, I added some explicit tests in the actor spec for `#attach_to_work`:
```ruby
    context 'without representative and thumbnail' do
      it 'assigns them (with persistence)' do
        actor.attach_to_work(work)
        expect(work.representative).to eq(file_set)
        expect(work.thumbnail).to eq(file_set)
        expect { work.reload }.not_to change { [work.representative, work.thumbnail] }
      end
    end

    context 'with representative and thumbnail' do
      it 'does not (re)assign them' do
        allow(work).to receive(:thumbnail_id).and_return('ab123c78h')
        allow(work).to receive(:representative_id).and_return('zz365c99q')
        expect(work).not_to receive(:representative=)
        expect(work).not_to receive(:thumbnail=)
        actor.attach_to_work(work)
      end
    end
```

I trust this is the last we'll have to talk about how the logic is.

File: app/controllers/hyrax/file_sets_controller.rb (hunk 5 above)
Comment (atz) [inline app/controllers/hyrax/file_sets_controller.rb]: @mjgiarlo The code you link to is all forked anyway:
- `ihrnexuslab`'s `update_metadata_from_upload_screen` requires a param!  That means they are already overriding the method that invokes it, too (and not calling `super`).  
- `sephirothkod`: same thing
- `HyrdraNorth` decided everything in their `FilesControllerBehavior` including this method would be `protected`... via a module, no less!  
- Duke has the cleanest implementation, but makes the method `public`.  Like others, it has decided an instance variable named `@generic_file` means something.  But it doesn't in Hyrax.

File: app/jobs/ingest_job.rb (hunk 6 above)
Comment (mjgiarlo) [inline app/jobs/ingest_job.rb]: @atz How about: `# We want the "lastmost hash", if any. It isn't particularly important, since the number of arguments is small (1-2), but it minimizes the number of times the detect block is evaluated (max once).`

Comment (mjgiarlo) [inline app/jobs/ingest_job.rb]: Feel free to rework/shorten/simplify.

File: app/jobs/ingest_job.rb (hunk 7 above)
Comment (mjgiarlo) [inline app/jobs/ingest_job.rb]: @atz What's happening here, as I currently understand it, is that we use `IngestJob` for two tasks: 1) to create a new work and 2) to upload a new version of a file to a work. We want notifications for both, but currently they're handled in different spots in the code, with only the latter triggered within the job. (The former is triggered by `Hyrax::Actors::BaseActor`.) The code we have now retains past behavior (triggering new version events when new versions are uploaded), so I'd be willing to punt this concern to a later date if it becomes problematic.

File: app/controllers/hyrax/file_sets_controller.rb (hunk 5 above)
Comment (mjgiarlo) [inline app/controllers/hyrax/file_sets_controller.rb]: @atz Those are admittedly all on Sufia, some older than others.

@jcoyne How much do you care about this change? Based on what I'm seeing in other repos, I'm not too worried about this complicating the CC to Hyrax bridge and thus I'm inclined to stop caring about it in the context of this PR.

File: spec/actors/hyrax/actors/file_set_actor_spec.rb (hunk 4 above)
Comment (mjgiarlo) [inline spec/actors/hyrax/actors/file_set_actor_spec.rb]: Great, thanks, @atz!

File: app/actors/hyrax/actors/file_set_actor.rb (hunk 3 above)
Comment (jcoyne) [inline app/actors/hyrax/actors/file_set_actor.rb]: Since this runs an asynchronous job, won't this end up with the Tempfile unavailable for the job?

File: app/controllers/hyrax/file_sets_controller.rb (hunk 5 above)
Comment (jcoyne) [inline app/controllers/hyrax/file_sets_controller.rb]: I don't really care about this change.  I do think we should endeavor to keep our PRs small and not change things that aren't related to the stated purpose of the PR.  I would have liked to have seen this change in a separate PR like "Reduce indirection in FileSetsController"

Comment (mjgiarlo) [inline app/controllers/hyrax/file_sets_controller.rb]: OK, let's say :+1:  to this change for now, then.

File: app/actors/hyrax/actors/file_set_actor.rb (hunk 3 above)
Comment (atz) [inline app/actors/hyrax/actors/file_set_actor.rb]: You are right that `IngestJob` won't work on a `Tempfile`.  But unlike its predecessor, this method doesn't attempt to pass the `Tempfile` directly to the job.  Instead it calls `IngestJob.perform_later(wrapper!(file, relation))`, where `wrapper!` effectively converts `file` to a persisted `JobIoWrapper` to match the signature of `IngestJob`.  Make sense?

File: app/jobs/ingest_job.rb (hunk 7 above)
Comment (atz) [inline app/jobs/ingest_job.rb]: @mjgiarlo: The job is invoked for both `create_content` and `update_content`.  Only the latter wants notifications (presumably because it is more targeted than the 100 notifications you might get from a single initial directory upload).  I don't know if it overlaps w/ `BaseActor` or not, but the two distinct uses is what prompted the option/param.

File: app/actors/hyrax/actors/file_set_actor.rb (hunk 3 above)
Comment (jcoyne) [inline app/actors/hyrax/actors/file_set_actor.rb]: Yes, the wrapper thing makes sense. I'm just calling out a potential problem with the Yard documentation.  I don't think we want to accept a Tempfile, because they aren't going to have much success with it (even though the exception wouldn't occur until the background job)

File: app/jobs/ingest_job.rb (hunk 7 above)
Comment (mjgiarlo) [inline app/jobs/ingest_job.rb]: @atz Right. At the moment, there are six event jobs around content changes:

https://github.com/samvera/hyrax/blob/master/config/initializers/hyrax_callbacks.rb#L2-L24

* `:after_create_concern` creates an event for every new work, and it fires from the actor stack: https://github.com/samvera/hyrax/blob/68527862df498aa9f407b909d4f41d781ba146dc/app/actors/hyrax/actors/base_actor.rb#L14
* `:after_create_fileset` creates an event when a fileset is attached to a work using `attach_to_work`: https://github.com/samvera/hyrax/blob/77140b38907158aaa4e30aae442ea5f04d0b1be2/app/actors/hyrax/actors/file_set_actor.rb#L58
* `:after_revert_content` creates an event when a fileset is reverted to a past version: https://github.com/samvera/hyrax/blob/77140b38907158aaa4e30aae442ea5f04d0b1be2/app/actors/hyrax/actors/file_set_actor.rb#L69
* `:after_update_content` you're well acquainted with
* `:after_update_metadata` creates an event when a work is updated (as distinct from when a fileset is updated), invoked by the actor stack: https://github.com/samvera/hyrax/blob/68527862df498aa9f407b909d4f41d781ba146dc/app/actors/hyrax/actors/base_actor.rb#L22
* `:after_destroy` creates an event when a work is destroyed, called from the works controller: https://github.com/samvera/hyrax/blob/45b988145d76dd5c2e659aa0cd53737e7d138c3a/app/controllers/concerns/hyrax/works_controller_behavior.rb#L117

Part of why we're using the callbacks in different spots in the codebase could be that some of our actors are meant to be used in a stack and others are meant to be used alone (more akin to "service objects"?). I'm definitely not suggesting this PR needs to tackle this problem. ;) I'm leaving this comment here to show that we considered changes to how we approach this but that we decided to punt for good reason.

File: app/actors/hyrax/actors/file_set_actor.rb (hunk 3 above)
Comment (mjgiarlo) [inline app/actors/hyrax/actors/file_set_actor.rb]: @atz @jcoyne Do y'all have a sense of when `Tempfile`s are used in this context? For instance, is this going to hose us in AWS-hosted environments?

Comment (jcoyne) [inline app/actors/hyrax/actors/file_set_actor.rb]: Tempfiles used to be used when we copied something from s3 to local. I don't know how they would be used now after the refactoring.

Comment (atz) [inline app/actors/hyrax/actors/file_set_actor.rb]: In practice, as currently used in the web app, we mostly get the fancier variety of params, so I'm OK with removing this from the YARD.  However, there is existing code referencing Tempfiles related to arkivo and `ImportUrlJob`.  If we want a technical fix here, it might involve: 
1. raise if given a Tempfile (even though on simplistic single-box inline systems, it would otherwise work)
1. automatically convert Tempfile to a `Hyrax::UploadedFile`
1. convert any remaining callers to passing non-Tempfile objects

I might be for some combination of 1 and 3 in a follow-up.

Note: there may be other kinds of "self destructing" file classes that will otherwise successfully pass through this method (and present the same issue jcoyne is talking about).

Comment (jcoyne) [inline app/actors/hyrax/actors/file_set_actor.rb]: I'm okay with just removing the documentation.  I understand this is Ruby and we can't prevent the user from shooting themselves in the foot, but we should at least not advertise something we know to be bad.
