### PR TITLE
deleted proxy is deleted even if page is refreshed.  Fixes issue #3542.

### LINKED ISSUE #3542: Deleting current proxy immediately after authorization fails
### Descriptive summary

Behavior observed on Hyrax v2.3.3 as well as on Nurax.

On the Manage Proxies page, after adding a proxy the user pops up under current proxy.  If you click on the "Delete Proxy" button the proxy will be removed from the Current Proxies button.  After refreshing the page, the proxy remains.

### Rationale

While normally you wouldn't want to immediately remove a proxy, it could be necessary in the event you accidentally add someone as there proxy.  In that case it's especially important to remove the proxy rather than fail silently which could allow the accidentally authorized user to make changes on their behalf.

### Expected behavior

Clicking Delete Proxy, actually removes that proxy

### Actual behavior

Click Delete Proxy removes proxy from page, but fails silently due to a bad path.

### Steps to reproduce the behavior

1. Visit the Manage Proxies page.
2. Authorize a user as a proxy
3. Refresh the manage proxies page
4. See the proxy reappear under Current Proxies

### Related work

We discovered this on our samvera/hyrax application here at the University of Cincinnati, and [integrated this change](https://github.com/uclibs/ucrate/pull/661/files) to fix it.

### PR DESCRIPTION
**Pull request by blancoj**
Fixes #3542

On the Manage Proxies page, after adding a proxy the user pops up under "Current Proxies" list with a delete button next to it. If you click on the "Delete Proxy" button the proxy will be removed from the Current Proxies list. But before this change, if you refreshed the page, the proxy was still being shown with the Delete button next to it.  This PR ensures that the proxy is actually deleted even after refreshing the page.

Guidance for testing, such as acceptance criteria or new user interface behaviors:
* Visit the Manage Proxies page.
* Authorize a user as a proxy
* Delete the user you have just made a proxy using the Delete button next to it
* Refresh the manage proxies page
* Verify the user is not shown under the  Current Proxies list

@samvera/hyrax-code-reviewers

### CODE REVIEW

File: spec/controllers/hyrax/depositors_controller_spec.rb [hunk 1]
```diff
@@ -62,6 +62,16 @@
           expect { redundant_request_to_grant_proxy }.not_to change { user.mailbox.inbox.count }
         end
       end
+
+      context "when a request to grant proxy is made to a user" do
+        let(:request_to_grant_proxy) { post :create, params: { user_id: user.user_key, grantee_id: grantee.user_key, format: 'json', use_route: :hyrax } }
+        let(:expected_delete_path) { "/users/" + user.user_key.gsub("\.", '-dot-') + "/depositors/" + grantee.user_key.gsub("\.", '-dot-') + "?locale=en" }
+
+        it "the user is made proxy, and the delete proxy button path is valid" do
```
Comment (jeremyf) [inline spec/controllers/hyrax/depositors_controller_spec.rb:70]: This test appears to be testing the change that makes the feature possible, and not necessarily the feature.  Please rework to test the feature

File: app/controllers/hyrax/depositors_controller.rb [hunk 2]
```diff
@@ -37,6 +37,10 @@ def destroy
 
     private
 
+    def sanitize_route_string(route)
```
Comment (jeremyf) [inline app/controllers/hyrax/depositors_controller.rb:40]: Could you add a comment about why this method? I think your PR helps give it context.  For those looking at it in the future, it would be helpful to give them insight into what's happening.

**Comment by jeremyf** [comment]
Interesting errors, those are ones that I'm encountering in my Postgresql branch.

They are a randomly failing set of errors.

**Comment by jeremyf** [comment]
@blancoj Can you rebase against master? There's a change that I believe will fix the erratic failing bugs.

**Comment by blancoj** [comment]
@jeremyf Just rebased it and it passed all the tests!
