### PR TITLE
Fix collection action menu edit behavior to go to edit instead of show

### LINKED ISSUE #2069: BUG Collections: clicking `Edit collection` in the action menu for an admin set should forward to edit form
### Descriptive summary

When a user clicks `Edit collection` in the action menu for an admin set, it should forward to the edit form for the admin set.  Right now, it forwards to the show page.

### Expected behavior

Dashboard -> Collections -> beside an admin set -> click action menu Edit collection

Should forward to admin set edit form:  `http://localhost:3000/admin/admin_sets/:id/edit`

### Actual behavior

Dashboard -> Collections -> beside an admin set -> click action menu Edit collection

Forward to admin set show page:  `http://localhost:3000/admin/admin_sets/:id`

### Steps to reproduce the behavior

1. Dashboard -> Collections
1. click action menu beside an admin set and select `Edit collection`

Verify forward to edit form

### Related work

#1508 - PR #1908 - Update code to handle edit action in index pages
#1968 Collections: Delete admin set should forward to my collections

### PR DESCRIPTION
**Pull request by gordonleacock**
Fixes #2069 

When a user clicks Edit collection in the action menu for an admin set, it should forward to the edit form for the admin set. Right now, it forwards to the show page.

_Expected behavior_
Dashboard -> Collections -> beside an admin set -> click action menu Edit collection

Should forward to admin set edit form: http://localhost:3000/admin/admin_sets/:id/edit

_Actual behavior_
Dashboard -> Collections -> beside an admin set -> click action menu Edit collection

Forward to admin set show page: http://localhost:3000/admin/admin_sets/:id

### CODE REVIEW

**Comment by gordonleacock** [comment]
Hi Mike - I fixed commit message.

**Comment by mjgiarlo** [comment]
@gordonleacock Hmmm, I'm not seeing it: https://github.com/samvera/hyrax/pull/2196/commits

**Comment by gordonleacock** [comment]
Thanks Mike - How does it look now?

File: app/controllers/hyrax/admin/admin_sets_controller.rb [hunk 1]
```diff
@@ -106,7 +106,7 @@ def create_admin_set
       def setup_form
         add_breadcrumb t(:'hyrax.controls.home'), root_path
         add_breadcrumb t(:'hyrax.dashboard.breadcrumbs.admin'), hyrax.dashboard_path
-        add_breadcrumb t(:'hyrax.admin.sidebar.admin_sets'), hyrax.admin_admin_sets_path
+        add_breadcrumb t(:'hyrax.dashboard.my.action.edit_admin_set'), hyrax.admin_admin_sets_path
```
Comment (jcoyne) [inline app/controllers/hyrax/admin/admin_sets_controller.rb]: You've changed the title here to say "Edit collection", but this goes to the index path.  Will that be confusing?

Comment (gordonleacock) [reply app/controllers/hyrax/admin/admin_sets_controller.rb]: Quite right - Expect an update to this PR.

File: app/controllers/hyrax/admin/admin_sets_controller.rb [hunk 2]
```diff
@@ -106,7 +106,7 @@ def create_admin_set
       def setup_form
         add_breadcrumb t(:'hyrax.controls.home'), root_path
         add_breadcrumb t(:'hyrax.dashboard.breadcrumbs.admin'), hyrax.dashboard_path
-        add_breadcrumb t(:'hyrax.admin.sidebar.admin_sets'), hyrax.admin_admin_sets_path
+        add_breadcrumb t(:'hyrax.dashboard.my.action.edit_admin_set'), hyrax.edit_admin_admin_set_path(:id)
```
Comment (jcoyne) [inline app/controllers/hyrax/admin/admin_sets_controller.rb]: Does this draw the correct link?  I'm not sure you can pass a symbol as the first argument.  I'm also wondering if this is the correct behavior for the `new` action, which also calls this method.

Comment (gordonleacock) [reply app/controllers/hyrax/admin/admin_sets_controller.rb]: Thanks @jcoyne I'll push up a fix sometime today.

**Comment by gordonleacock** [comment]
To get travis to pass I've had to move some changes from [WIP] Coll 2071 - Fix admin_set controller to add proper breadcrumbs #2140 to this PR.

**Comment by gordonleacock** [comment]
@jcoyne and @mjgiarlo - Let me know if more changes are needed or this can be merged. Thanks!

File: app/controllers/hyrax/dashboard/collections_controller.rb [hunk 3]
```diff
@@ -62,7 +62,7 @@ def new
         collection_type_id = params[:collection_type_id]
         add_breadcrumb t(:'hyrax.controls.home'), root_path
         add_breadcrumb t(:'hyrax.dashboard.breadcrumbs.admin'), hyrax.dashboard_path
-        add_breadcrumb t(:'hyrax.dashboard.collections.new.header'), request.path
+        add_breadcrumb t(:'hyrax.dashboard.collections.new.header') + " " + @collection.collection_type.title, request.path
```
Comment (elrayle) [inline app/controllers/hyrax/dashboard/collections_controller.rb]: PR #2071 is fixing the breadcrumbs.  I'd prefer not to mix these two PRs.  Can you remove this change from here?

File: app/controllers/hyrax/admin/admin_sets_controller.rb [hunk 4]
```diff
@@ -106,7 +106,7 @@ def create_admin_set
       def setup_form
         add_breadcrumb t(:'hyrax.controls.home'), root_path
         add_breadcrumb t(:'hyrax.dashboard.breadcrumbs.admin'), hyrax.dashboard_path
-        add_breadcrumb t(:'hyrax.admin.sidebar.admin_sets'), hyrax.admin_admin_sets_path
+        add_breadcrumb t(:'hyrax.dashboard.my.collections'), hyrax.my_collections_path
```
Comment (elrayle) [inline app/controllers/hyrax/admin/admin_sets_controller.rb]: PR #2071 is fixing the breadcrumbs.  I'd prefer not to mix these two PRs.  Can you remove this change from here?

File: app/views/hyrax/dashboard/collections/new.html.erb [hunk 5]
```diff
@@ -1,10 +1,14 @@
-<% provide :page_title, construct_page_title( t('.header', type_title: @collection.collection_type.title) ) %>
+<% provide :page_title, construct_page_title( t('.header', type_title:  @collection.collection_type.title) ) %>
```
Comment (elrayle) [inline app/views/hyrax/dashboard/collections/new.html.erb]: I'm not sure I understand the need for changes to this file for issue #2069.  Can you provide info on why these are needed?

File: config/locales/hyrax.en.yml [hunk 6]
```diff
@@ -575,7 +575,7 @@ en:
             collection_title: "Collection Title"
           this_collection_in_other_collections_description: "You can add this collection to other collections as a sub-collection."
         new:
-          header: "New %{type_title}"
+          header: "New"
```
Comment (elrayle) [inline config/locales/hyrax.en.yml]: Don't think this change will be needed if you take out the changes to app/views/hyrax/dashboard/collections/new.html.erb.

File: app/views/hyrax/dashboard/collections/new.html.erb [hunk 7]
```diff
@@ -1,10 +1,14 @@
...
 <% end %>
 
 <div class="row">
   <div class="col-md-12">
     <%= render 'form' %>
   </div>
 </div>
+
+
+#t(:'hyrax.dashboard.collections.new.header') + " " + @collection.collection_type.title
```
Comment (jcoyne) [inline app/views/hyrax/dashboard/collections/new.html.erb]: What's going on here?

File: app/views/hyrax/dashboard/collections/new.html.erb [hunk 8]
```diff
@@ -1,10 +1,14 @@
-<% provide :page_title, construct_page_title( t('.header', type_title: @collection.collection_type.title) ) %>
+<% provide :page_title, construct_page_title( t('.header', type_title:  @collection.collection_type.title) ) %>
 <% provide :page_header do %>
-  <h1><span class="fa fa-edit"></span> <%= t('.header', type_title: @collection.collection_type.title) %> </h1>
+  <% a_title = t(:'hyrax.dashboard.collections.new.header') + " " + @collection.collection_type.title %>
```
Comment (jcoyne) [inline app/views/hyrax/dashboard/collections/new.html.erb]: Why are you putting this in a string? You can use erb:
```
<%= t(:'hyrax.dashboard.collections.new.header') %> <%= @collection.collection_type.title %>
```

File: app/controllers/hyrax/admin/admin_sets_controller.rb (hunk 4 above)
Comment (gordonleacock) [reply app/controllers/hyrax/admin/admin_sets_controller.rb]: Sure.

File: app/views/hyrax/dashboard/collections/new.html.erb (hunk 5 above)
Comment (gordonleacock) [reply app/views/hyrax/dashboard/collections/new.html.erb]: Okay, reverted.

File: app/controllers/hyrax/admin/admin_sets_controller.rb (hunk 4 above)
Comment (gordonleacock) [reply app/controllers/hyrax/admin/admin_sets_controller.rb]: Okay, reverted. It wasn't passing travis ci without some of these changes.

File: app/controllers/hyrax/dashboard/collections_controller.rb (hunk 3 above)
Comment (gordonleacock) [reply app/controllers/hyrax/dashboard/collections_controller.rb]: Okay, reverted.

File: config/locales/hyrax.en.yml (hunk 6 above)
Comment (gordonleacock) [reply config/locales/hyrax.en.yml]: Okay, reverted. It is a bug but I can fix it for 2071 if you want or we could make it a separate issue.

File: app/views/hyrax/dashboard/collections/new.html.erb (hunk 5 above)
Comment (gordonleacock) [reply app/views/hyrax/dashboard/collections/new.html.erb]: Reverted.

File: app/views/hyrax/dashboard/collections/new.html.erb (hunk 8 above)
Comment (gordonleacock) [reply app/views/hyrax/dashboard/collections/new.html.erb]: Thanks @jcoyne! @elrayle - Do you want me to revert this change too.

File: app/views/hyrax/dashboard/collections/new.html.erb (hunk 7 above)
Comment (gordonleacock) [reply app/views/hyrax/dashboard/collections/new.html.erb]: Left over junk! Deleted.

File: app/views/hyrax/dashboard/collections/new.html.erb [hunk 9]
```diff
@@ -1,6 +1,7 @@
-<% provide :page_title, construct_page_title( t('.header', type_title: @collection.collection_type.title) ) %>
+<% provide :page_title, construct_page_title( t('.header') ) %>
+
 <% provide :page_header do %>
-  <h1><span class="fa fa-edit"></span> <%= t('.header', type_title: @collection.collection_type.title) %> </h1>
+  <h1><span class="fa fa-edit"></span> <%= t('.header') %></h1>
```
Comment (elrayle) [inline app/views/hyrax/dashboard/collections/new.html.erb]: Not sure why this file is changed?  If you revert this back to what it is in collections-sprint branch, the failing feature test passes.

Comment (gordonleacock) [reply app/views/hyrax/dashboard/collections/new.html.erb]: I tried to revert it but grabbed the master version of this file by mistake. Correcting and pushing again in a minute!

**Comment by gordonleacock** [comment]
@elrayle - I made this much simpler and it passes now. Thanks for reining my changes in!
