### PR TITLE
[WIP] Coll 2071 - Fix admin_set controller to add proper breadcrumbs

### LINKED ISSUE #2071: Collections: Bread crumbs for admin set show page should use collections links
### Descriptive summary

Change bread crumbs for admin set show page to match those for collection show page.

### Rationale

Admin sets are simulating being just another collection, so the bread crumbs should look like the admin set is just another collection.

### Expected behavior

`admin/admin_sets/:id` breadcrumbs should be...
* My Dashboard - forward to `dashboard`
* Your Collections - forward to `dashboard/my/collections`
* _admin set title_ (no link)

### Actual behavior

`admin/admin_sets/:id` breadcrumbs are...
* Home - forward to `/`
* Administration - forward to `dashboard`
* translation missing:... - forward to `admin/admin_sets`
* View Set (no link)

### Steps to reproduce the behavior

1. login as admin user
1. create an admin set with title `'Test Admin Set'`
1. Dashboard -> Collections -> click title of the new admin set

- [ ] Verify that the breadcrumbs are...
  * My Dashboard - forward to `dashboard`
  * Your Collections - forward to `dashboard/my/collections`
  * 'Test Admin Set'  (no link)

### PR DESCRIPTION
**Pull request by gordonleacock**
Fixes #2071 

Descriptive summary

Change bread crumbs for admin set show page to match those for collection show page.

Rationale
Admin sets are simulating being just another collection, so the bread crumbs should look like the admin set is just another collection.

Expected behavior
admin/admin_sets/:id breadcrumbs should be...

The consistent set of breadcrumbs starts with...
* Home - `/`
* Administration - `/dashboard`
* Your Collections - `/dashboard/my/collections`
* admin set/collection title

### CODE REVIEW

File: app/controllers/hyrax/admin/admin_sets_controller.rb [hunk 1]
```diff
@@ -22,10 +22,9 @@ class Admin::AdminSetsController < ApplicationController
     self.admin_set_create_service = AdminSetCreateService
 
     def show
-      add_breadcrumb t(:'hyrax.controls.home'), root_path
-      add_breadcrumb t(:'hyrax.dashboard.breadcrumbs.admin'), hyrax.dashboard_path
-      add_breadcrumb t(:'hyrax.admin.sidebar.admin_sets'), hyrax.admin_admin_sets_path
-      add_breadcrumb t(:'hyrax.admin.admin_sets.show.breadcrumb'), request.path
+      add_breadcrumb t(:'hyrax.dashboard.breadcrumbs.dashboard'), hyrax.dashboard_path
```
Comment (jcoyne) [inline app/controllers/hyrax/admin/admin_sets_controller.rb]: Is there a reason not to use `hyrax.toolbar.dashboard.menu` here?

File: app/controllers/hyrax/admin/admin_sets_controller.rb [hunk 2]
```diff
@@ -22,10 +22,9 @@ class Admin::AdminSetsController < ApplicationController
...
+      add_breadcrumb t('hyrax.dashboard.my.collections'), hyrax.my_collections_path
+      add_breadcrumb "<em>#{@admin_set.title.first}</em>", "#"
```
Comment (jcoyne) [inline app/controllers/hyrax/admin/admin_sets_controller.rb]: Have you tested that this doesn't get escaped as it's not HTML safe?

File: app/controllers/hyrax/admin/admin_sets_controller.rb [hunk 3]
```diff
@@ -22,10 +22,9 @@ class Admin::AdminSetsController < ApplicationController
     self.admin_set_create_service = AdminSetCreateService
 
     def show
-      add_breadcrumb t(:'hyrax.controls.home'), root_path
-      add_breadcrumb t(:'hyrax.dashboard.breadcrumbs.admin'), hyrax.dashboard_path
-      add_breadcrumb t(:'hyrax.admin.sidebar.admin_sets'), hyrax.admin_admin_sets_path
-      add_breadcrumb t(:'hyrax.admin.admin_sets.show.breadcrumb'), request.path
```
Comment (jcoyne) [inline app/controllers/hyrax/admin/admin_sets_controller.rb]: Should this be removed from the translation files (all of them)?

File: spec/controllers/hyrax/admin/admin_sets_controller_spec.rb [hunk 4]
```diff
@@ -184,6 +184,20 @@
           expect(AdminSet.exists?(admin_set.id)).to be true
         end
       end
+
+      context "with a referer" do
+        before do
+          request.env['HTTP_REFERER'] = 'http://test.host/foo'
```
Comment (jcoyne) [inline spec/controllers/hyrax/admin/admin_sets_controller_spec.rb]: why is the referrer important here?

File: app/controllers/hyrax/admin/admin_sets_controller.rb (hunk 1 above)
Comment (gordonleacock) [reply app/controllers/hyrax/admin/admin_sets_controller.rb]: Thanks @jcoyne I'll check that option out.

File: app/controllers/hyrax/admin/admin_sets_controller.rb (hunk 2 above)
Comment (gordonleacock) [reply app/controllers/hyrax/admin/admin_sets_controller.rb]: Thanks @jcoyne! I added .html_safe and rubocop complained, so I removed it.

File: spec/controllers/hyrax/admin/admin_sets_controller_spec.rb (hunk 4 above)
Comment (gordonleacock) [reply spec/controllers/hyrax/admin/admin_sets_controller_spec.rb]: Okay, if it is not needed, I'll remove it. I was following the pattern from: spec/controllers/hyrax/dashboard/collections_controller_spec.rb
Thanks for pointing that out.

File: config/locales/hyrax.en.yml [hunk 5]
```diff
@@ -494,6 +494,7 @@ en:
       authorize_proxies:        "Authorize Proxies"
       breadcrumbs:
         admin:                  "Administration"
+        dashboard:              "Dashboard"
```
Comment (elrayle) [inline config/locales/hyrax.en.yml]: This won't be needed if you re-use the dashboard link suggested above.

File: app/controllers/hyrax/admin/admin_sets_controller.rb (hunk 2 above)
Comment (elrayle) [reply app/controllers/hyrax/admin/admin_sets_controller.rb]: Collections use this for the show page final breadcrumb...

```
add_breadcrumb presenter.to_s, polymorphic_path(presenter)
```

And works uses this, which is basically the same...
```
add_breadcrumb presenter.to_s, main_app.polymorphic_path(presenter)
```

File: app/controllers/hyrax/admin/admin_sets_controller.rb (hunk 1 above)
Comment (jcoyne) [reply app/controllers/hyrax/admin/admin_sets_controller.rb]: Yes, that one that @elrayle suggests is an even better option.

File: app/controllers/hyrax/admin/admin_sets_controller.rb (hunk 3 above)
Comment (gordonleacock) [reply app/controllers/hyrax/admin/admin_sets_controller.rb]: Good idea - Cleaned up.

**Comment by gordonleacock** [comment]
@elrayle - Please review. 
1. My tests (spec/controllers/hyrax/admin/admin_sets_controller_spec.rb and spec/controllers/hyrax/collections_controller_spec.rb) aren't working properly and I could use pointers on how to fix them.
2. Please let me know if the admin set behavior looks correct.
3. I went down a rabbit home trying to change the collections breadcrumbs. This wasn't as simple as the admin_set breadcrumbs. Started changing app/controllers/concerns/hyrax/breadcrumbs.rb  and app/controllers/concerns/hyrax/breadcrumbs_for_collections.rb, but didn't want to proceed unless you thought this was the right direction.

File: app/controllers/hyrax/admin/admin_sets_controller.rb (hunk 1 above)
Comment (gordonleacock) [reply app/controllers/hyrax/admin/admin_sets_controller.rb]: Resovled

File: app/controllers/hyrax/admin/admin_sets_controller.rb (hunk 2 above)
Comment (gordonleacock) [reply app/controllers/hyrax/admin/admin_sets_controller.rb]: Resolved

File: spec/controllers/hyrax/collections_controller_spec.rb [hunk 6]
```diff
@@ -78,7 +79,9 @@
         end
 
         it "sets breadcrumbs" do
-          expect(controller).to receive(:add_breadcrumb).with('My Dashboard', Hyrax::Engine.routes.url_helpers.dashboard_path(locale: 'en'))
+          expect(controller).to
```
Comment (jcoyne) [inline spec/controllers/hyrax/collections_controller_spec.rb]: You can't have a line break here.  The ruby interpreter doesn't understand how to parse this correctly.

try this instead: 
```ruby
expect(controller).to receive(:add_breadcrumb)
  .with(...)
```

File: app/views/hyrax/dashboard/collections/new.html.erb [hunk 7]
```diff
@@ -1,6 +1,8 @@
 <% provide :page_title, construct_page_title( t('.header', type_title: @collection.collection_type.title) ) %>
+<% a_title = t(:'hyrax.dashboard.collections.new.header') + " " + @collection.collection_type.title %>
```
Comment (jcoyne) [inline app/views/hyrax/dashboard/collections/new.html.erb]: why are you setting this variable here? It looks like you're only using it once. Can you just inline that stuff on line 5?

File: spec/controllers/hyrax/collections_controller_spec.rb [hunk 8]
```diff
@@ -31,7 +31,7 @@
       end
 
       it "returns the collection and its members", :with_nested_reindexing do # rubocop:disable RSpec/ExampleLength
-        expect(controller).to receive(:add_breadcrumb).with(I18n.t('hyrax.dashboard.title'), Hyrax::Engine.routes.url_helpers.dashboard_path(locale: 'en'))
+        expect(controller).to receive(:add_breadcrumb).with(I18n.t('hyrax.controls.home'), Hyrax::Engine.routes.url_helpers.root_path(locale: 'en'))
```
Comment (jcoyne) [inline spec/controllers/hyrax/collections_controller_spec.rb]: You changed this test. But you didn't change `CollectionsController#show` to have this behavior.

File: spec/controllers/hyrax/collections_controller_spec.rb [hunk 9]
```diff
@@ -66,7 +66,8 @@
 
       context "without a referer" do
         it "sets breadcrumbs" do
-          expect(controller).to receive(:add_breadcrumb).with(I18n.t('hyrax.dashboard.title'), Hyrax::Engine.routes.url_helpers.dashboard_path(locale: 'en'))
+          expect(controller).to
```
Comment (jcoyne) [inline spec/controllers/hyrax/collections_controller_spec.rb]: You can't have a line break here.  The ruby interpreter doesn't understand how to parse this correctly.

try this instead: 
```ruby
expect(controller).to receive(:add_breadcrumb)
  .with(...)
```

File: app/views/hyrax/dashboard/collections/new.html.erb (hunk 7 above)
Comment (gordonleacock) [reply app/views/hyrax/dashboard/collections/new.html.erb]: I tried but it that code kept giving me only "New" without the rest of the string. Here's what I tried: <h1><span class="fa fa-edit"></span> <%= t('.header', type_title: t(:'hyrax.dashboard.collections.new.header') + " " + @collection.collection_type.title) %> </h1>

Comment (gordonleacock) [reply app/views/hyrax/dashboard/collections/new.html.erb]: Moving this change to the PR: Fix collection action menu edit behavior to go to edit instead of show #2196, because it was blocking travis ci there. If you have a better way, I'm glad to do it.

Comment (jcoyne) [reply app/views/hyrax/dashboard/collections/new.html.erb]: Like so:
```
<%=t(:'hyrax.dashboard.collections.new.header') %> <%= @collection.collection_type.title %> 
```

Comment (gordonleacock) [reply app/views/hyrax/dashboard/collections/new.html.erb]: @elrayle - Do you want me to change the header problem on the new page here or should it be a separate issue?

**Comment by gordonleacock** [comment]
@elrayle - Not sure why I'm getting these travis ci failures now that I've cut back my changes to just one file.
