### PR TITLE
deprecate #source_model in permission template; use #source instead

### LINKED ISSUE #5406: Valkyrie: Hyrax::PermissionTemplate #source_model uses ActiveFedora::Base.find
### Descriptive summary

Hyrax::PermissionTemplate should use the Hyrax.query_service to find and load the object.  This will work for both ActiveFedora wings adapter and for other Valkyrie adapters.

The error is seen when editing an admin set.  The view `hyrax/admin/admin_sets/_form_visibility.html.erb` gets access to `Hyrax::PermissionTemplate` thru the `Hyrax::PermissionTemplateForm`.  It tries to retrieve the model from `Hyrax::PermissionTemplate #source_model`.

### Rationale

PermissionTemplate methods should work for both ActiveFedora and Valkyrie

### Expected behavior

Editing a Hyrax::AdministrativeSet and clicking the Participants tab should load the tab in the edit form.

### Actual behavior

Editing a Hyrax::AdministrativeSet and clicking the Participants tab gets an `Hyrax::ObjectNotFoundError` while loading the tab in the edit form.

image

#### Prerequisites:

Edit `/config/initializers/hyrax.rb` and set:
1. set the admin set model
```
  config.admin_set_model = "Hyrax::AdministrativeSet"
```
2. restart rails server

#### To reproduce:

1. navigate to Dashboard -> Collections
2. click button: New Collection
3. select type: Admin Set
3. click button: Create Collection
3. set Title: My Admin Set (or other meaningful name)
4. click Save (this loads the editor for the admin set)
5. click the Participants tab

The error will occur as the tab tries to load.

NOTE: There may be other errors once this error is resolved.

### Related work

See related issues in Issue #5326 UBER: Hyrax-Valkyrization MVP

### PR DESCRIPTION
**Pull request by elrayle**
Fixes #5406

The issue is addressed by changes in `PermissionTemplateForm`
* changing to use `PermissionTemplate#source` instead of `PermissionTemplate#source_method`
* calling `PermissionTemplate#reset_access_controls_for(collection: source)` instead of `source_model.reset_access_controls!` in `#update_access`.

### Add note suggesting to use `PermissionTemplate#source` instead of `PermissionTemplate#source_method`

`PermissionTemplate#source_method` uses `ActiveFedora::Base.find` to get an instance based on `source_id`.  It always returns an `ActiveFedora::Base`.

`PermissionTemplate#source` uses `Hyrax.query_service.find_by` to get an instance based on `source_id`.  It always returns a `Valkyrie::Resource`.

The only place `#source_method` is called within Hyrax code is `Hyrax::Forms::PermissionTemplateForm`.  Usages include:
* #source_model - makes this method available from PermissionTemplateForm through delegation.  This was moved to a method to allow for note recommending use of #source
* #reset_access_controls! - This method calls `source_model.reset_access_controls!` which requires an ActiveFedora::Base object.  This is a deprecated method.  It was not changed other than to update the delegation warning to recommend use of `PermissionTemplate#reset_access_controls_for` instead of `PermissionTempate#reset_access_controls.
* #update_access - This called `source_model.reset_access_controls!` which requires an ActiveFedora::Base object provided by `source_model`.  It was updated to call `PermissionTemplate #reset_access_controls_for` which can receive both ActiveFedora::Base or Valkyrie::Resource objects.  So it can be (and is) passed `source`.

### Deprecate `PermissionTemplate#reset_access_controls`, use `PermissionTemplate#reset_access_controls_for` instead

Similarly, `Hyrax::PermissionTemplate#reset_access_controls` was only called from `Hyrax::Forms::PermissionTemplateForm`.  It is worth noting that the replacement `PermissionTemplate#reset_access_controls_for` is already in use in all other classes that want to reset access.

@samvera/hyrax-code-reviewers

### CODE REVIEW

File: app/models/hyrax/permission_template.rb [hunk 1]
```diff
@@ -79,11 +79,16 @@ def source
...
     # A bit of an analogue for a `belongs_to :source_model` as it crosses from Fedora to the DB
-    # @return [AdminSet, ::Collection]
-    # @raise [Hyrax::ObjectNotFoundError] when neither an AdminSet or Collection is found
+    # @return [AdminSet, ::Collection, Hyrax::AdministrativeSet, Hyrax::PcmdCollection]
+    # @raise [Hyrax::ObjectNotFoundError] when neither an admin set or collection is found
     def source_model
-      ActiveFedora::Base.find(source_id)
-    rescue ActiveFedora::ObjectNotFoundError
+      if Hyrax.config.disable_wings
+        source
```
Comment (elrayle) [inline app/models/hyrax/permission_template.rb:86]: The `#source` method just above uses `query_service.find_by(:id)`.  So I didn't repeat that code here.  It seems likely that once fully Valkyrized, `#source_model` will be deprecated and replaced by `#source`.

File: app/models/hyrax/permission_template.rb [hunk 2]
```diff
@@ -79,11 +79,16 @@ def source
...
+      else
+        Hyrax.query_service.find_by_alternate_identifier(alternate_identifier: source_id,
+                                                         use_valkyrie: Hyrax.config.use_valkyrie?)
+      end
```
Comment (elrayle) [inline app/models/hyrax/permission_template.rb:90]: When `use_valkyrie?` is `false`, `find_by_alternate_identifier` will return an `AdminSet` or `Collection` (ActiveFedora).  Otherwise, this returns a `Hyrax::AdministrativeSet` or `Hyrax::PcdmCollection` (Valkyrie).

File: app/forms/hyrax/forms/permission_template_form.rb [hunk 3]
```diff
@@ -73,8 +73,13 @@ def update(attributes)
       # Copy this access to the permissions of the Admin Set or Collection and to
       # the WorkflowResponsibilities of the active workflow if this is an Admin Set
       def update_access(remove_agent: false)
-        source_model.reset_access_controls!
-        update_workflow_responsibilities(remove_agent: remove_agent) if source_model.is_a?(AdminSet)
+        case source_model
+        when Valkyrie::Resource
+          source_model.permission_manager.acl.save
+        else
+          source_model.reset_access_controls!
```
Comment (no-reply) [inline app/forms/hyrax/forms/permission_template_form.rb:80]: isn't there an existing pattern for replacing `reset_access_controls!`?

i think it might be `reset_access_controls_for(collection: source)`, established in db58e27e787f87dd930d8ac7b04e28741712d90c

File: spec/controllers/hyrax/admin/permission_template_accesses_controller_spec.rb [hunk 4]
```diff
@@ -4,6 +4,7 @@
   let(:hyrax) { Hyrax::Engine.routes.url_helpers }
   let(:permission_template_access) { FactoryBot.create(:permission_template_access) }
   let(:source_id) { permission_template_access.permission_template.source_id }
+  let(:user_liz) { FactoryBot.create(:user, email: 'liz@example.com') }
```
Comment (elrayle) [inline spec/controllers/hyrax/admin/permission_template_accesses_controller_spec.rb:7]: Without a FactoryBot created user, some of the actions did not have their methods executed because they failed `load_and_authorize_resource` in the class.

File: app/forms/hyrax/forms/permission_template_form.rb (hunk 3 above)
Comment (elrayle) [reply app/forms/hyrax/forms/permission_template_form.rb]: Switched to this pattern.

File: app/models/hyrax/permission_template.rb (hunk 1 above)
Comment (no-reply) [reply app/models/hyrax/permission_template.rb:86]: if this is to be deprecated (which seems right to me) why is it changing? would it be okay to switch to using `source` uniformly in `PermissionTemplateForm` instead?

File: app/models/hyrax/permission_template.rb [hunk 5]
```diff
@@ -225,7 +222,7 @@ def read_groups
     #   visibility when applying permission template ACLs
     # @return [Boolean]
     def reset_access_controls(interpret_visibility: false)
-      reset_access_controls_for(collection: source_model,
+      reset_access_controls_for(collection: source,
```
Comment (no-reply) [inline app/models/hyrax/permission_template.rb:225]: this shouldn't change, i think. it was implemented to ensure the implementation for `reset_access_controls` stayed the same for AF models, after the refactor.

File: app/forms/hyrax/forms/permission_template_form.rb [hunk 6]
```diff
@@ -7,16 +7,16 @@ class PermissionTemplateForm
       self.model_class = PermissionTemplate
       self.terms = []
       delegate :access_grants, :access_grants_attributes=, :release_date, :release_period, :visibility, to: :model
-      delegate :available_workflows, :active_workflow, :source_model, to: :model
+      delegate :available_workflows, :active_workflow, :source, to: :model
```
Comment (elrayle) [inline app/forms/hyrax/forms/permission_template_form.rb:10]: `:source_model` is still available.  It is defined as a method to allow for a deprecation message.

File: app/models/hyrax/permission_template.rb (hunk 1 above)
Comment (elrayle) [reply app/models/hyrax/permission_template.rb]: I can't see any reason not to deprecate `#source_model` now.  The 3rd commit does that.  The description in this PR identifies the uses of `#source_model` and how they were handled as part of the deprecation.

File: app/models/hyrax/permission_template.rb (hunk 5 above)
Comment (elrayle) [reply app/models/hyrax/permission_template.rb]: I changed this back to use `source_model`.

File: app/models/admin_set.rb [hunk 7]
```diff
@@ -87,12 +87,12 @@ def active_workflow
...
 
   ##
-  # @deprecated use PermissionTemplate#reset_access_controls instead
+  # @deprecated use PermissionTemplate#reset_access_controls_for instead
   #
   # Calculate and update who should have edit access based on who
   # has "manage" access in the PermissionTemplateAccess
   def reset_access_controls!
-    Deprecation.warn("reset_access_controls! is deprecated; use PermissionTemplate#reset_access_controls instead.")
+    Deprecation.warn("reset_access_controls! is deprecated; use PermissionTemplate#reset_access_controls_for instead.")
```
Comment (elrayle) [inline app/models/admin_set.rb:95]: There are a number of deprecated methods that were updated to use `reset_access_controls_for` but the deprecation message said to use `reset_access_controls`.  These were updated.

File: app/forms/hyrax/forms/permission_template_form.rb [hunk 8]
```diff
@@ -7,16 +7,12 @@ class PermissionTemplateForm
       self.model_class = PermissionTemplate
       self.terms = []
       delegate :access_grants, :access_grants_attributes=, :release_date, :release_period, :visibility, to: :model
-      delegate :available_workflows, :active_workflow, :source_model, to: :model
-
-      # @return [#to_s] the primary key of the associated admin_set or collection
-      # def source_id (because you might come looking for this method)
-      delegate :id, to: :source_model, prefix: :source
+      delegate :available_workflows, :active_workflow, :source, :source_id, to: :model
```
Comment (elrayle) [inline app/forms/hyrax/forms/permission_template_form.rb:10]: The previous delegate to get the `id` from `source_model` resulted in an unnecessary population of the `source_model` just to get the `id` which is already available from the template using `source_id`.  So this removes the original delation and adds a direct delegate to `:source_id`.

NOTE: There is still access to the `source_model` in the template even though the delegation was removed.  There is a method named `#source_model` defined later in this class that include a note recommending use of `#source` unless the ActiveFedora model is really needed.

File: app/forms/hyrax/forms/permission_template_form.rb [hunk 9]
```diff
@@ -7,16 +7,12 @@ class PermissionTemplateForm
...
 
       ##
-      # @deprecated  use PermissionTemplate#reset_access_controls instead.
+      # @deprecated  use PermissionTemplate#reset_access_controls_for instead.
       def reset_access_controls!
-        Deprecation.warn("reset_access_controls! is deprecated; use PermissionTemplate#reset_access_controls instead.")
+        Deprecation.warn("reset_access_controls! is deprecated; use PermissionTemplate#reset_access_controls_for instead.")
```
Comment (elrayle) [inline app/forms/hyrax/forms/permission_template_form.rb:15]: The long term method that should be used is `#reset_access_controls_for`, so the deprecation notice was updated.

File: app/forms/hyrax/forms/permission_template_form.rb [hunk 10]
```diff
@@ -73,8 +69,8 @@ def update(attributes)
       # Copy this access to the permissions of the Admin Set or Collection and to
       # the WorkflowResponsibilities of the active workflow if this is an Admin Set
       def update_access(remove_agent: false)
-        source_model.reset_access_controls!
-        update_workflow_responsibilities(remove_agent: remove_agent) if source_model.is_a?(AdminSet)
+        model.reset_access_controls_for(collection: source)
```
Comment (elrayle) [inline app/forms/hyrax/forms/permission_template_form.rb:72]: This is part of the fix of the issue.  `source_model` uses `ActiveFedora::Base.find` which is not available when using Valkyrie postgres adapter.  `source` uses `Hyrax.query_service.find_by`.

File: app/forms/hyrax/forms/permission_template_form.rb [hunk 11]
```diff
@@ -85,6 +81,18 @@ def remove_access!(permission_template_access)
...
 
+      ##
+      # A bit of an analogue for a `belongs_to :source_model` as it crosses from Fedora to the DB
+      # @return [AdminSet, ::Collection]
+      # @raise [Hyrax::ObjectNotFoundError] when neither an AdminSet or Collection is found
+      # @note This method will eventually be replaced by #source which returns a Hyrax::Resource
+      #   object.  Many methods are equally able to process both Hyrax::Resource and
+      #   ActiveFedora::Base.  Only call this method if you need the ActiveFedora::Base object.
+      # @see #source
+      def source_model # rubocop:disable Rails/Delegate
```
Comment (elrayle) [inline app/forms/hyrax/forms/permission_template_form.rb:92]: This is defined here instead of as a delegate to allow the note encouraging use of `#source` instead of `#source_model`.

**Review by no-reply — APPROVED** [review]

**Comment by no-reply** [comment]
thank you for working through this one! i really like how it shaped up and hope you do too!
