### PR TITLE
Remove depositors access to FileSets in mediated deposit

### LINKED ISSUE #1091: Depositor can edit the fileset after deposit has been approved (mediated workflow)
### Descriptive summary

After a depositor has made a deposit and this has been approved, they can no longer edit the work. But they are still able to edit the fileset.

[ observed in Hyku v1.0.0.beta1 ]

### Rationale

The behaviour needs to be consistent across works and their contained filesets.

### Expected behavior

User can no longer edit Work and contained FileSets.

### Actual behavior

User can edit FileSet.

### Steps to reproduce the behavior

1. Submit as a 'depositing' user to the mediated worfklow
2. Approver approves the deposit
3. Depositing user returns to the work and edits fileset

### PR DESCRIPTION
**Pull request by jcoyne**
Fixes #1091

@samvera/hyrax-code-reviewers

### CODE REVIEW

File: app/jobs/hyrax/revoke_edit_from_members_job.rb [hunk 1]
```diff
@@ -0,0 +1,15 @@
...
+  # Revokes edit access for the supplied user for the members attached to a work
+  class RevokeEditFromMembersJob < ApplicationJob
+    queue_as Hyrax.config.ingest_queue_name
+
+    # @param [ActiveFedora::Base] work - the work object
+    # @param [String] user_key - the user to remove
+    def perform(work, user_key)
+      # Iterate over ids because reifying objects is slow.
+      work.member_ids.each do |file_set_id|
+        RevokeEditJob.perform_now(file_set_id, user_key)
```
Comment (mjgiarlo) [inline app/jobs/hyrax/revoke_edit_from_members_job.rb]: Will this also act on child works? If so, `file_set_id` may cause confusion in the future.

File: app/jobs/hyrax/revoke_edit_job.rb [hunk 2]
```diff
@@ -0,0 +1,14 @@
+module Hyrax
+  # Revokes the user's edit access on the provided FileSet
+  class RevokeEditJob < ApplicationJob
+    queue_as Hyrax.config.ingest_queue_name
+
+    # @param [String] file_set_id - the identifier of the object to revoke access from
+    # @param [String] user_key - the user to remove
+    def perform(file_set_id, user_key)
```
Comment (mjgiarlo) [inline app/jobs/hyrax/revoke_edit_job.rb]: Same comment as above.

File: app/jobs/hyrax/revoke_edit_from_members_job.rb (hunk 1 above)
Comment (darrenleeweber) [inline app/jobs/hyrax/revoke_edit_from_members_job.rb]: If the method in `RevokeEditJob` is always called with `perform_now` and only ever called here, then move that perform method into a private method on this job and dispense with the extra job.

Comment (jcoyne) [inline app/jobs/hyrax/revoke_edit_from_members_job.rb]: @darrenleeweber If we do that, that means a single failure in updating one of the members would halt the whole batch. This way, the failure is isolated and can be restarted independently.

Comment (jcoyne) [inline app/jobs/hyrax/revoke_edit_from_members_job.rb]: @mjgiarlo I'm not sure what we should do about child works. Should I explicitly include them or exclude them?

Comment (darrenleeweber) [inline app/jobs/hyrax/revoke_edit_from_members_job.rb]: @jcoyne - so your saying the whole thing does not need to be an atomic "transaction"?  It's OK if any one of the users is not removed?  As it is, I _guess_ this parent job will never fail.

Comment (jcoyne) [inline app/jobs/hyrax/revoke_edit_from_members_job.rb]: @darrenleeweber There is no way in ActiveFedora to use a transaction (mostly because there is no support for transactions in Solr).

Comment (mjgiarlo) [inline app/jobs/hyrax/revoke_edit_from_members_job.rb]: @jcoyne I suspect that excluding them until we have to analyze the effects and side-effects of that change can be explored. Write up a new issue and focus on FSes here?

Comment (jcoyne) [inline app/jobs/hyrax/revoke_edit_from_members_job.rb]: Okay, I'll make some changes. Here's the ticket for child works: https://github.com/samvera/hyrax/issues/1213
